<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Widget\Dob $block */
/*
  <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
  ->setDate($block->getCustomer()->getDob())
  ->toHtml() ?>

  For checkout/onepage/billing.phtml:

  <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
  ->setDate($block->getCustomer()->getDob())
  ->setFieldIdFormat('billing:%s')
  ->setFieldNameFormat('billing[%s]')
  ->toHtml() ?>

  NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css. Alternatively we could calculate widths
  automatically using block input parameters.
 */

$fieldCssClass = 'field date field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>

<div class="<?= $block->escapeHtmlAttr($fieldCssClass) ?> form-group">

    <!--    <div class="control customer-dob">-->

 <?php if(isset($_SESSION['customer_base']['customer_id'])) { ?>
      <label class="input_label" for="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"><span><?= $block->escapeHtml($block->getLabel()) ?></span></label>
      <div class="input-group custom-dob-field"><?= $block->getFieldHtml() ?></div>
    
    
 <?php } else { ?>
<?= $block->getFieldHtml() ?>
    <label class="input_label" for="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"><span><?= $block->escapeHtml($block->getLabel()) ?></span></label>
    <?php if ($_message = $block->getAdditionalDescription()) : ?>
        <div class="note"><?= $block->escapeHtml($_message) ?></div>
    <?php endif; ?>
    <!--    </div>-->
    <!--    <label class="label" for="<?php // $block->escapeHtmlAttr($block->getHtmlId()) ?>"><span><?php // $block->escapeHtml($block->getLabel()) ?></span></label>-->
    <?php } ?>
</div>
