<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Ship to multiple address template
 *
 * @var $block \Magento\Multishipping\Block\Checkout\Addresses
 */
?>
<form id="checkout_multishipping_form"
      data-mage-init='{
          "multiShipping":{},
          "cartUpdate": {
               "validationURL": "/multishipping/checkout/checkItems",
               "eventName": "updateMulticartItemQty"
          }}'
      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
      method="post"
      class="multicheckout address form">
    <input type="hidden" name="continue" value="0" id="can_continue_flag"/>
    <input type="hidden" name="new_address" value="0" id="add_new_address_flag"/>
    <div class="block table-wrapper">
        
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Please select a shipping address for applicable items.')) ?></strong>
        </div>
        <div class="block-content">
            <table class="items data table table-bordered" id="multiship-addresses-table">
                
                <thead>
                <tr>
                    <th class="col product" scope="col"><?= $block->escapeHtml(__('Product')) ?></th>
                    <th class="col qty" scope="col"><?= $block->escapeHtml(__('Qty')) ?></th>
                    <th class="col address" scope="col"><?= $block->escapeHtml(__('Send To')) ?></th>
                    <th class="col actions" scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($block->getItems() as $_index => $_item): ?>
                    <?php if ($_item->getQuoteItem()) : ?>
                        <tr>
                            <td class="col product" data-th="<?= $block->escapeHtml(__('Product')) ?>">
                                <?= $block->getItemHtml($_item->getQuoteItem()) ?>
                            </td>
                            <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
                                <div class="field qty">
    <!--                                <label for="ship-<?php // $block->escapeHtml($_index) ?>-<?= $block->escapeHtml($_item->getQuoteItemId()) ?>-qty"
                                           class="label">
                                        <span><?php // $block->escapeHtml(__('Qty')) ?></span>
                                    </label>-->
                                    <div class="control">
                                        <input type="number"
                                               data-multiship-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                                               id="ship-<?= $block->escapeHtml($_index) ?>-<?= $block->escapeHtml($_item->getQuoteItemId()) ?>-qty"
                                               name="ship[<?= $block->escapeHtml($_index) ?>][<?= $block->escapeHtml($_item->getQuoteItemId()) ?>][qty]"
                                               value="<?= $block->escapeHtml($_item->getQty()) ?>"
                                               size="2" min="1"
                                               class="input-text qty"
                                               data-validate="{number: true}"/>
                                    </div>
                                </div>
                            </td>
                            <td class="col address" data-th="<?= $block->escapeHtml(__('Send To')) ?>">
                                <?php if ($_item->getProduct()->getIsVirtual()): ?>
                                    <div class="applicable">
                                        <?= $block->escapeHtml(__('A shipping selection is not applicable.')) ?>
                                    </div>
                                <?php else: ?>
                                    <div class="field address">
    <!--                                    <label for="ship_<?php // $block->escapeHtml($_index) ?>_<?php // $block->escapeHtml($_item->getQuoteItemId()) ?>_address"
                                               class="label">
                                            <span><?php // $block->escapeHtml(__('Send To')) ?></span>
                                        </label>-->
                                        <div class="control">
                                            <?= $block->getAddressesHtmlSelect($_item, $_index) ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </td>
                            <td class="col actions" data-th="<?= $block->escapeHtml(__('Actions')) ?>">
                                <a href="<?= $block->escapeUrl($block->getItemDeleteUrl($_item)) ?>"
                                   title="<?= $block->escapeHtml(__('Remove Item')) ?>"
                                   class="action delete"
                                   data-multiship-item-remove="">
                                    <span class="fa fa-close"><?= $block->escapeHtml(__('')) ?></span>
                                </a>
                            </td>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="clearfix actions-toolbar">  
        <div class="primary">
            <button type="submit"
                    title="<?= $block->escapeHtml(__('Go to Shipping Information')) ?>"
                    class="btn action primary continue<?php if ($block->isContinueDisabled()):?> disabled<?php endif; ?>"
                    data-role="can-continue"
                    data-flag="1"
                <?php if ($block->isContinueDisabled()):?>
                    disabled="disabled"
                <?php endif; ?>>
                <span><?= $block->escapeHtml(__('Go to Shipping Information')) ?></span>
            </button>
            <button type="submit"
                    data-multiship-item-update=""
                    class="btn action update"
                    data-role="can-continue"
                    data-flag="0">
                <span><?= $block->escapeHtml(__('Update Qty &amp; Addresses')) ?></span>
            </button>
            <button type="button"
                    title="<?= $block->escapeHtml(__('Enter a New Address')) ?>"
                    class="btn action add"
                    data-role="add-new-address">
                <span><?= $block->escapeHtml(__('Enter a New Address')) ?></span>
            </button>
            <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>"
               class="btn action back">
                <span><?= $block->escapeHtml(__('Back to Shopping Cart')) ?></span>
            </a>
            
        </div>
    </div>
</form>
