<?php $helper = $this->helper("Rptech\Buynow\Helper\Data"); ?>
<?php $addtocartId = $helper->getConfig('buynow/general/addtocart_id'); ?>
<?php $buttonTitle = $helper->getConfig('buynow/general/button_title'); ?>
<?php $formId = $addtocartId ? $addtocartId : "product_addtocart_form"; ?>
<div class="buynow-button">
    <button type="submit" title="<?php /* @escapeNotVerified */ echo __($buttonTitle) ?>" id="buy-now" class="btn action primary" data-bind='mageInit: {"Rptech_Buynow/js/buy-now":{"form": "#<?php echo $formId; ?>"}}'>
        <span><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
    </button>
</div>