<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
$catalogHelperData = $this->helper('Magento\Catalog\Helper\Data');
$categoryObject = $catalogHelperData->getCategory();
$categoryId = $categoryObject->getId();
?>
<?php if (!$_productCollection->count()): ?>
    <?php if ($categoryId == 375): ?><div class="message info empty"><div><?= /* @escapeNotVerified */ __('No Projects available.') ?></div></div>
	<?php else: ?>
		<div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
	<?php endif; ?>
<?php else:
    ?>
    <?php if ($categoryId == 375): ?>
            <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="col-lg-9 col-md-9 products-wrapper">
        <div class="col-xs-12 title-wrapper clearfix">
            <div class="mb-filter">
                <button class="btn"><i class="fa fa-filter"></i> Filter</button>
            </div> 

            <h3 class="title"><?php //echo $this->getLayer()->getCurrentCategory()->getName()   ?></h3>

            <div class="custom-select-my floater-left">
                <?= $block->getToolbarHtml() ?>
            </div>

        </div>
        <div class="products-row equalheight_wrapper clearfix">
            <?php foreach ($_productCollection as $_product): ?>
                <div class="col-md-4 col-sm-4 col-xs-6 product-box">
                    <div class="product-inner-box product<?= $block->escapeHtml($_product->getId()) ?>">
                        <div class="txt-content">
                            <div class="proBox equalheight">
                                <div class="proBoxInner">
                                    <div class="imgDiv">
                                        <div class="img-box">
                                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product-thumbnail" target="_blank">
                                                <img class="product-img img-responsive" src="<?= $block->getImage($_product, $image)->getImageUrl(); ?>">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="proInfoDiv">
                                        <h3 class="product-title">
                                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" target="_blank">
                                                <?php 
                                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
											   echo $_productNameStripped;
                                                /* if(strlen($_productNameStripped) > 25){
                                                    echo substr($_productNameStripped, 0, 25).'...';
                                                }else{
                                                    echo $_productNameStripped;
                                                } */
                                                ?>
                                            </a>
                                        </h3>
                                        <div class="product-desc">
                                            <?php 
                                                $_productDescStripped = $_product->getShortDescription();
                                                if(strlen($_productDescStripped) > 100){
                                                    echo substr($_productDescStripped, 0, 100).'...';
                                                }else{
                                                    echo $_productDescStripped;
                                                }
                                                ?>      
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="industry">
                            <?php $industryName  = $_product->getAttributeText('industries');
                            echo $industryName;
                            ?>
                        </div>
						<div class="location">
							<?php $locationName = $_product->getResource()->getAttribute('location')->getFrontend()->getValue($_product);
							echo $locationName; ?>
						</div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php echo $block->getToolbarHtml() ?>
    </div>
    
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
            "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
            }
            }
            }
        </script>
    <?php endif; ?>
        <?php else: ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="col-lg-9 col-md-9 products-wrapper">
        <div class="col-xs-12 title-wrapper clearfix">
            <div class="mb-filter">
                <button class="btn"><i class="fa fa-filter"></i> Filter</button>
            </div> 

            <h3 class="title"><?php //echo $this->getLayer()->getCurrentCategory()->getName()   ?></h3>

            <div class="custom-select-my floater-left">
                <?= $block->getToolbarHtml() ?>
            </div>

        </div>
        <div class="products-row equalheight_wrapper clearfix">
            <?php foreach ($_productCollection as $_product): ?>
                <div class="col-md-4 col-sm-4 col-xs-6 product-box">
                    <div class="product-inner-box product<?= $block->escapeHtml($_product->getId()) ?>">
                        <div class="txt-content equalheight">
                            <div class="img-box">
                                <button  data-role="add-to-links" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' class="btn btn-wishlist action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"><i class="fa fa-heart"></i></button>
                                <!--<a class="btn btn-wishlist" href="#"><i class="fa fa-heart" aria-hidden="true"></i></a>-->
                                <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product-thumbnail">
                                    <img class="product-img img-responsive" src="<?= $block->getImage($_product, $image)->getImageUrl(); ?>">
                                </a>
                            </div>
                            <h3 class="product-title">
                                <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?php 
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    if(strlen($_productNameStripped) > 25){
                                        echo substr($_productNameStripped, 0, 25).'...';
                                    }else{
                                        echo $_productNameStripped;
                                    }
                                    ?>
                                </a>
                            </h3>
                            <p class="product-desc">
                                <?php 
                                    $_productDescStripped = $_product->getShortDescription();
                                    if(strlen($_productDescStripped) > 30){
                                        echo substr($_productDescStripped, 0, 30).'...';
                                    }else{
                                        echo $_productDescStripped;
                                    }
                                    ?>
                            </p>
                            <div class="price-tag" style="font-weight: 800;">
                                <span class="price" style="float: none;"><?php echo $priceHelper->currency($_product->getFinalPrice(), true, false); ?></span>
                            
                                <p style="width: 55%;float: right;position: relative;color: #2b2b2b;font-weight: 400;">
                                    <?php if ($_product->getSpecialPrice() && (strtotime($_product->getSpecialFromDate()) <= strtotime(date('Y-m-d')) && strtotime($_product->getSpecialTodate()) >= strtotime(date('Y-m-d')) )) { 
                                        $calculateDiscountPerce = (($_product->getPrice() - $_product->getSpecialPrice()) / $_product->getPrice() ) * 100;
                                    ?>
                                    <span style="text-decoration: line-through;float: left;" ><?= ($_product->getSpecialPrice()) ? $priceHelper->currency($_product->getPrice(), true, false) : ""; ?></span>
                                    <span class="offers" style="float: right;"><?= ($calculateDiscountPerce) ? round($calculateDiscountPerce) : ""; ?>% Off</span>
                                    <?php }?>
                                </p>
                            </div>
                        </div>
                        <div class="clearfix btn-wrapper">
                            <span style="display: none" class="prosku"><?php echo $_product->getSku(); ?></span>
                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="btn btn-view">View</a>
                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                <?= $block->getBlockHtml('formkey') ?>
                                <?php
                                $sell_status = $_product->getResource()->getAttribute('sell_status')->getFrontend()->getValue($_product);
                                if ($sell_status == 'Yes' && $_product->getFinalPrice() > 0 && $_product->getIsSalable()) {
                                    ?>
                                    <button type="submit"
                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                        class="action tocart primary btn btn-cart">
                                        <span><i class="fa fa-shopping-cart"></i><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                    </button>
                                <?php } else { ?>
                                <span style="display: none" class="prosku"><?php echo $_product->getSku(); ?></span>
                                    <a class="btn btn-enq" id="product<?= $block->escapeHtml($_product->getId()) ?>">Send Enquiry</a>
                                <?php } ?>
                            </form>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php echo $block->getToolbarHtml() ?>
    </div>
    
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
            "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
            }
            }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php endif; ?>