<?php
$typeClass = "";
$message = "";
if (isset($_SESSION['success_msg'])) {
	$typeClass = 'message-success success';
	$message = $_SESSION['success_msg'];
	unset($_SESSION['success_msg']);
} elseif (isset($_SESSION['error_msg'])) {
	$typeClass = 'message-error error';
	$message = $_SESSION['error_msg'];
	unset($_SESSION['error_msg']);
} elseif (isset($_SESSION['notice_msg'])) {
	$typeClass = 'message-notice notice';
	$message = $_SESSION['notice_msg'];
	unset($_SESSION['notice_msg']);
} elseif (isset($_SESSION['warning_msg'])) {
	$typeClass = 'message-warning warning';
	$message = $_SESSION['warning_msg'];
	unset($_SESSION['warning_msg']);
}
?>
<div class="page messages">
	<div class="messages">
		<div class="message <?= $typeClass ?>">
			<div><?= $message ?></div>
		</div>
	</div>
</div>