<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Radio */ ?>
<?php $_option = $block->getOption(); ?>
<?php $_selections = $_option->getSelections(); ?>
<?php $_default = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>

<div class="field option <?= ($_option->getRequired()) ? ' required' : '' ?>">
    <legend class="legend title" >
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </legend>
    <div class="control">
        <div class="nested options-list custom-radio-wrapper">
            <?php if ($block->showSingle()): ?>
                <?= /* @escapeNotVerified */ $block->getSelectionTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?= (int) $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?= (int) $_option->getId() ?>]"
                       value="<?= (int) $_selections[0]->getSelectionId() ?>"
                       id="bundle-option-<?= (int) $_option->getId() ?>-<?= (int) $_selections[0]->getSelectionId() ?>"
                       checked="checked"
                       />
                   <?php else: ?>
                       <?php if (!$_option->getRequired()): ?>
                    <div class="field choice case-item">
                        <input type="radio"
                               class="radio product bundle option"
                               id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>"
                               name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                               data-selector="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                               <?= ($_default && $_default->isSalable()) ? '' : ' checked="checked" ' ?>
                               value=""/>
                        <label class="label" for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>">
                            <span><?= /* @escapeNotVerified */ __('None') ?></span>
                        </label>
                    </div>
                <?php endif; ?>
                <?php
                foreach ($_selections as $_selection):
                    $_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
                    $image = $_imageHelper->init($_selection, 'small_image', ['type' => 'small_image'])->keepAspectRatio(true)->resize('50', '50')->getUrl();
                    ?>
		
                    <div class="field choice case-item">
                        <label class="label"
                               for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>">
        <!--                            <span><?= /* @escapeNotVerified */ $block->getSelectionTitlePrice($_selection) ?></span>-->
                            <div class="bundle-option-image"><img src="<?php echo $image; ?>" /></div>
			    <?php echo $_selection->getName(); ?><br>
			    <?php // echo $_selection->getShortDescription(); ?>
                        </label>
                        <input type="radio"
                               class="radio product bundle option change-container-classname"
                               id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>"
                               <?php if ($_option->getRequired()) echo 'data-validate="{\'validate-one-required-by-name\':true}"' ?>
                               name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                               data-selector="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                               <?php if ($block->isSelected($_selection)) echo ' checked="checked"' ?>
                               <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>
                               value="<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>"/>

                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-container"></div>
            <?php endif; ?>
            <div class="field qty qty-holder">
                <label class="label" for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-qty-input">
                    <span><?= /* @escapeNotVerified */ __('Quantity') ?></span>
                </label>
                <div class="control">
                    <input <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?>
                        id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-qty-input"
                        class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>"
                        type="number"
                        name="bundle_option_qty[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                        data-selector="bundle_option_qty[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                        value="<?= /* @escapeNotVerified */ $_defaultQty ?>"/>
                </div>
            </div>
        </div>
    </div>
</div>
