<div id="myModal" class="modal ajax-login-form">
  <!-- Modal content -->
    <div class="<?php if($block->getLayoutType()){echo 'ultimate';}else{ echo 'mobile-modal-content';} ?>">
        <?php include ($block->getTemplateFile('Magecomp_Mobilelogin::image.phtml')) ?>
        <div class="<?php if($block->getLayoutType()) echo 'right' ?>">
    <div class="closediv"><span class="close"></span></div>
    <div class="ajax-login-conten">
        <div class="page_title">
            <span><?php echo __('Login') ?></span>
        </div>
        <ul id="login-type">
            <li class="login-type-first"><a href="#ajaxotplogin" id="loginwithotp"><?php echo __('Login With Otp') ?></a></li>
            <li class="login-type-last"><a href="#ajaxpasswordlogin" id="loginwithajax"><?php echo __('Login With Password') ?></a></li>
        </ul>
        <div  id="ajaxotplogin" class="login-container"><?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magecomp_Mobilelogin::ajaxotplogin.phtml")->toHtml(); ?></div>
        <div  id="ajaxpasswordlogin" class="login-container"><?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magecomp_Mobilelogin::ajaxpasswordlogin.phtml")->toHtml(); ?></div>
    </div>
  </div>
 </div>
</div>
<script>
require(['jquery','mage/translate','jquery/ui','mage/mage','mage/validation'], function($,$t)
{
    var ajoinput = document.querySelector("#loginotpmob"),
        loginerrorMsg = document.querySelector("#login-mob-error-msg");
    // here, the index maps to the error code returned from getValidationError - see readme
    var loginerrorMap = [$t("Invalid number"), $t("Invalid country code"), $t("Too short"), $t("Too long"), $t("Invalid number")];

    // initialise plugin
    var ajoiti = window.intlTelInput(ajoinput, {
        utilsScript: "<?php echo $this->getViewFileUrl('Magecomp_Mobilelogin::js/utils.js'); ?>"
    });

    jQuery.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
        countryCode = (resp && resp.country) ? resp.country : "";
        ajoiti.setCountry("IN");
    });

    var reset = function() {
        ajoinput.classList.remove("error");
        loginerrorMsg.innerHTML = "";
    };

    // on blur: validate
    ajoinput.addEventListener('blur', function() {
        reset();
        if (ajoinput.value.trim()) {
            if (ajoiti.isValidNumber()) {
				loginerrorMsg.innerHTML = "";
            } else {
                var errorCode = ajoiti.getValidationError();
                loginerrorMsg.innerHTML = loginerrorMap[errorCode];
            }
        }
    });
});
</script>
