<?php
$mobileblock = $this->getLayout()->createBlock('Magecomp\Mobilelogin\Block\Mobilelogin');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
?>
<?php if($mobileblock->isEnable()):
?>
<div class="create-account-page-main-div fieldset">
	    <!-- <legend class="legend"><span>Mobile Verification</span></legend> -->
        <input type="hidden" value="<?php echo $block->getUrl("mobilelogin/index/sentotpbyreg"); ?>" class="setdotpurl" />
        <input type="hidden" value="<?php echo $block->getUrl("mobilelogin/index/ajaxcheckregotp"); ?>" class="checkotpurl" />
    	<div id="create-account-page" class="login-window account-login">
        	<div class="mobileget">
				<div class="otp-content fieldset">
                	 <span class="field required">
                        <label for="mobileget" class="label required">
                     	  <span><?php echo __('Mobile Number') ?></span>
                        </label>
                     </span>
                	<input type="text" value="" id="mobile-mobileget" class="mobnumber" name="mobile-mobileget" maxlength="12"/>
                    <input type="hidden" value="" id="regi-mobilenumber" name="mobilenumber" />
                    <input type="hidden" value="" id="countryreg" name="countryreg" />
                    <div class="mobileotpsenderror error1 error">
                      <span><?php echo __("Please Enter Valid Mobile.");?></span>
                    </div>
                    <div class="mobileExist error1 error">
                        <span><?php echo __("Mobile Number Already Exist.");?></span>
                    </div>
                    <div class="blankerror error1 error" id="blankpage_customer_register">
                            <span><?php echo __("Required fields cannot be empty");?></span>
                    </div>
                    <div class="mobileNotValid error1 error" id="mobileNotValid">
                            <span><?php echo __("Please Enter Valid Mobile Number");?></span>
                    </div> 
                 </div>
                 <div class="model-bottom"> 
                    <div class="submitbtnajax" id="submitbtnajax">
                        <input type="button" class="regi-sendotp button primary action" value="<?php echo __("Send Otp");?>" />
                    </div>
                     <div class="progress-indicator">
                             <span class="please-wait" id="reg-sms-please-wait">
                                <img src="<?php echo 
							$block->getViewFileUrl('Magecomp_Mobilelogin::images/ajax-loader.gif');?>" class="v-middle" alt=""/>
                            </span>
                        </div>
                </div>
            </div>
            <div class="otpverify" id="otpverify">
				<div class="otp-content fieldset">
                	<span class="field required">
                    <label for="mobile-otp" class="label">
                     	<span><?php echo __('Enter OTP') ?></span>
                     </label>
                    </span>
                    <span class="create-account-resend-otp" id="resend-otp-data">
                        <label for="resend-mobile-otp" class="label">
                            <span class='resend'><?php echo __("Resend OTP");?></span>
                            <span class='sending' id="sending"><?php echo __("Sending OTP...");?></span>
                         </label>
                    </span>
                	<input type="password" value="" id="mobile-otp" maxlength="<?php echo $block->getOtpStringlenght() ?>"/>
                    <div class="checkotperror error1 error">
                	<span><?php echo __("Incorrect OTP, Please Verify Again.");?></span>
                    </div>
                    <div class="blankerror blankotperror error1 error">
                        <span><?php echo __("Required fields cannot be empty.");?></span>
                    </div>
               <div class="model-bottom">
                    <div class="submitbtnajax" id="submitbtnajax1">
                        <input type="button" class="mobileverifyotp button primary action" value="<?php echo __('Verify OTP') ?>" />
                    </div>
               </div>
               <div class="progress-indicator">
                   <span class="please-wait" id="reg-otp-verify-please-wait">
                     <img src="<?php echo 
                  $block->getViewFileUrl('Magecomp_Mobilelogin::images/ajax-loader.gif');?>" class="v-middle" alt="Please Wait"/>
                  </span>
               </div>
            </div>
 </div>
<div class="customer-progress-indicator" id="customer-progress-indicator">
   <span class="customer-please-wait" id="customer-register-wait">
           <img src="<?php echo
             $block->getViewFileUrl('Magecomp_Mobilelogin::images/ajax-loader.gif');?>" class="v-middle" alt="Please Wait"/>
     </span>
</div>
<script>
require(['jquery','mage/translate','jquery/ui','mage/mage','mage/validation'], function($,$t) {
    var checkoutData = 0;  
    jQuery("#resend-otp-data").click(function (e) {
        checkoutData = 1;
        sendOtp();
        jQuery("#reg-sms-please-wait").css('display','none');
    });

    jQuery(".regi-sendotp").click(function (e) {
        sendOtp();

    });
    function sendOtp() {
         var regimobile = jQuery("#mobile-mobileget").val();
        var url = jQuery(".setdotpurl").val();
        jQuery(".blankerror").css('display','none');
        jQuery(".mobileNotValid").css('display','none');
        jQuery(".mobileotpsenderror").css('display','none');
        jQuery(".mobileExist").css('display','none');

        jQuery(".resend").css('display','none');
        jQuery(".sending").css('display','block');


        if(!regimobile){
            jQuery(".blankerror").css('display','block');

            return false;
        }
        /*if(validateMobile(regimobile) == false){
            jQuery(".mobileNotValid").css('display','block');
            return false;
        }*/
        var countrycode=jQuery('#create-account-page #countryreg').val().replace('+','');
        var mobile=countrycode.concat(regimobile);

        jQuery(".sendotp").css('display','none');
        jQuery("#reg-sms-please-wait").css('display','block');
        jQuery(this).prop('disabled',true);
        
        jQuery.ajax({
            url: url,
            type:'GET',
            data:{mobile:mobile,checkout:1,checkoutData:checkoutData},
            success: function (data) {
                jQuery(".sendotp").css('display','block');
                jQuery("#reg-sms-please-wait").css('display','none');
                if(data == 'true'){
                    jQuery("#createmobile").val(mobile);
                    jQuery(".mobileget").css('display','block');
                    jQuery(".regi-sendotp").css('display','none');
                    document.getElementById("mobile-mobileget").readOnly = true;
                    jQuery(".otpverify").css('display','block');
                    jQuery(".resend").css('display','block');
                    jQuery(".sending").css('display','none');
                    jQuery("#regi-mobilenumber").val(mobile);

                }/*else if(data == 'exist'){
                    jQuery(".mobileExist").css('display','block');
                }*/else{
                    jQuery(".mobileotpsenderror").css('display','block');
                }
                jQuery('.regi-sendotp').prop('disabled',false);
            },
            error: function () {

                jQuery(".sendotp").css('display','block');
                jQuery("#reg-sms-please-wait").css('display','none');
                jQuery(this).prop('disabled',false);
            }
        });
    }
    /*function validateMobile(mobile) {
        var filter = /^((\+[1-9]{1,4}[ \-]*)|(\([0-9]{2,3}\)[ \-]*)|([0-9]{2,4})[ \-]*)*?[0-9]{3,4}?[ \-]*[0-9]{3,4}?$/;

        if (filter.test(mobile)) {
            if(mobile.length >= 10 && mobile.length <= 13){
                var validate = true;
            } else {
                var validate = false;
            }
        }
        else {
            var validate = false;
        }
        return validate;
    }*/
    jQuery(".mobileverifyotp").click(function (e) {
        var otp =  jQuery("#mobile-otp").val();
        var mobile = jQuery("#mobile-mobileget").val();
        jQuery(".blankotperror").css('display','none');
        jQuery(".error").css('display','none');
        if(isBlank(otp) == false){
            jQuery(".blankotperror").css('display','block');
            return false;
        }
        var countrycode=jQuery('#create-account-page #countryreg').val().replace('+','');
        mobile=countrycode.concat(mobile);
        jQuery(".checkotperror").css('display','none');
        jQuery("#reg-otp-verify-please-wait").css('display','block');
        jQuery(".verifyotp").css('display','none');
        jQuery(this).prop('disabled',true);
        jQuery.ajax({
            url: jQuery(".checkotpurl").val(),
            type: 'GET',
            data:{otp:otp,mobile:mobile},
            success: function (data) {
                jQuery(".verifyotp").css('display','block');
                jQuery("#reg-otp-verify-please-wait").css('display','none');
                if(data == 'true'){
                    jQuery('div[name="shippingAddress.telephone"]').find('[name="telephone"]').val(jQuery('#mobile-mobileget').val());
                    jQuery('div[name="shippingAddress.telephone"]').find('[name="telephone"]').trigger("change");
                    jQuery("#createotp").val(otp);
                    jQuery(".otpverify").css('display','none');
                    jQuery(".registraionform").css('display','block');
                    jQuery(".submit").prop('disabled', false);

                }else{
                    jQuery(".checkotperror").css('display','block');
                }
                jQuery(".blankotperror").css('display','none');
                jQuery('.mobileverifyotp').prop('disabled',false);
            },
            error: function () {
                jQuery("#reg-otp-verify-please-wait").css('display','none');
                jQuery(".verifyotp").css('display','block');
                jQuery(this).prop('disabled',false);
            }
        });
    });
    function isBlank(value) {
        if(!value) {
            return false;
        }
    }
    var custreginput = document.querySelector("#mobile-mobileget"),
        custregerrorMsg = document.querySelector("#mobileNotValid");
    // here, the index maps to the error code returned from getValidationError - see readme
    var custregerrorMap = [$t("Invalid number"), $t("Invalid country code"), $t("Too short"), $t("Too long"), $t("Invalid number")];

    // initialise plugin
    var custregiti = window.intlTelInput(custreginput, {
        utilsScript: "<?php echo $this->getViewFileUrl('Magecomp_Mobilelogin::js/utils.js'); ?>"
    });

    jQuery.get('https://ipinfo.io', function() {}, "jsonp").always(function(resp) {
        custreginputcountryCode = (resp && resp.country) ? resp.country : "";
        custregiti.setCountry("IN");
    });

    var reset = function() {
        custreginput.classList.remove("error");
        custregerrorMsg.innerHTML = "";
    };

    // on blur: validate
    custreginput.addEventListener('blur', function() {
        reset();
        if (custreginput.value.trim()) {
            if (custregiti.isValidNumber()) {
            } else {
                var custregerrorCode = custregiti.getValidationError();
                custregerrorMsg.innerHTML = custregerrorMap[custregerrorCode];

            }
        }
    });
});
</script>
<?php endif; ?>