 <!-- <div class="avail-check">
	<form name="pincode_checker" class="pincode" id="pincode_checker" action="<?php echo $this->getUrl('pincode/index/index'); ?>" method="post" data-bind='mageInit: {"validation":{}}'>
		<input type="text" maxlength="6" name="pincode_check" id="pincode_check" required />
		<button type="submit" id="checkpincode" class="btn" data-bind='mageInit: {"checker":{}}'>Pincode Check<span id="spanpinloader" style="display: none;"><img class="pincodeloaderImg" src="<?php echo $this->getViewFileUrl('images/pincodeloader.gif'); ?>"></span>
		</button>

		<div class="successDiv" style="color: green;">
			<span id="showpincodemsg"></span>
		</div>

		<div class="errorDiv" style="color: red;">
			<span id="errorMsg"></span>
		</div>
	</form>
</div>
<style type="text/css">
	label#pincode_check-error{
		color: red;
    	text-transform: none;
    	font-weight:  normal;
	}
</style> -->