<div class="block block-collapsible-nav">
    <div class="block-title">
        <strong><span><?php echo __('My Account'); ?></span></strong>
    </div>
    <div class="content block-collapsible-nav-content">
        <ul class="nav items">
        <?php $_links = $block->getLinks(); ?>
        <?php $_index = 1; ?>
        <?php $_count = count($_links); ?>
        <?php foreach ($_links as $_link): ?>
            <?php $_last = ($_index++ >= $_count); ?>
            <?php if ($block->isActive($_link)): ?>
                <li class="nav items current<?php echo ($_last ? ' last' : '') ?>"><strong><?php echo $_link->getLabel() ?></strong></li>
            <?php else: ?>
                <li class="nav items <?php echo ($_last ? ' class="last"' : '') ?>"><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </div>
</div>