<?php
$poID = $this->getRequest()->getParam('id');
$poCollection = $this->loadPurchaseOrder($poID);
$poData = $poCollection->getData();
$poiData = $this->getPOModel()->getProducts($poCollection);

$poCommentsCol = $this->getPOModel()->getComments($poCollection);
$srIncrIdArr = $this->getPOModel()->getStockReceivedIds($poCollection);
$invoiceIdArr = $this->getPOModel()->getInvoiceIds($poCollection);


$priceHelper = $this->getPriceingHelper();
$currencyCode = $block->getCurrentStore()->getCurrentCurrencyCode();
$_localeCurrency = $block->getCurrencyInterface();
$currencySymbol = $_localeCurrency->getCurrency($currencyCode)->getSymbol();
$_bizHelper = $block->getBizHelper();
$supName = $this->getSupplierFullName($poData['supplier_id']);

?>
<?php if ($_bizHelper->isEnable()) : ?>
<div class="content-header">
	<h3 class="icon-head head-adminhtml-purchaseorders"><?php echo __($poData['purchase_order_id'])." | ".date("M d, Y h:i:s A",strtotime(__($poData['created_at']))); ?></h3>
</div>
<section class="admin__page-section">
	<div class="admin__page-section-content">
		<div class="admin__page-section-title">
			<h4 class="title"> <?php echo __('Purchase Order Items') ?> </h4>
		</div>
		<div class="admin__control-table-wrapper">
			<table cellspacing="0" border="1" class="admin__control-table data-table" width="100%">
				<thead>
					<tr class="headings">
						<th><?php echo __('Name'); ?></th>
						<th><?php echo __('SKU'); ?></th>
						<th><?php echo __('Qty Pur.'); ?></th>
						<th><?php echo __('Qty Rec.'); ?></th>
						<th><?php echo __('Unit Cost'); ?></th>
						<th><?php echo __('Row Total'); ?></th>
					</tr>
				</thead>
				<?php
				for($i=0;$i<count($poiData);$i++) {
					?>
					<tr>
						<td><?php echo $poiData[$i]['product_name']; ?></td>
						<td><?php echo $poiData[$i]['product_sku']; ?></td>
						<td><?php echo $poiData[$i]['qty_purchased']; ?></td>						
						<td><?php if($poiData[$i]['qty_received'] == '') echo 0; else echo $poiData[$i]['qty_received']; ?></td>
						<td><?php echo $priceHelper->currency($poiData[$i]['cost'], true, true); ?></td>
						<td><?php echo $priceHelper->currency($poiData[$i]['row_total'], true, true); ?></td>
					</tr>
					<?php
				}
				?>
			</table>
		</div>
	</div>
</section>

<section class="admin__page-section">
	<div class="admin__page-section-content">
		<div class="admin__page-section-title">
			<h4 class="title"> <?php echo __('Additional Details') ?> </h4>
		</div>
		<div class="admin__control-table-wrapper">
			<table cellspacing="0" class="admin__control-table data-table" width="100%" 
			style="border: 1px solid #444; border-radius:0; ">
			<tbody>
				<tr>
					<td style="padding:5px;"><strong><?php echo __('Supplier:'); ?></strong></td>
					<td><?php echo $supName; ?></td>
				</tr>
				<tr>
					<td style="padding:5px;"><strong><?php echo __('PO Status:'); ?></strong></td>
					<td><?php echo $poData['status']; ?></td>
				</tr>
				<tr>
					<td style="padding:5px;"><strong><?php echo __('Sales Order(s): '); ?></strong></td>
					<td><?php
						if ($poData['sales_order_id']) {
							$getIncrIds = explode(",", $poData['sales_order_id']);
							for ($i = 0; $i < count($getIncrIds); $i++) {
								$orderModel = $block->getOrder();
								$order = $orderModel->loadByIncrementId($getIncrIds[$i]);
								$id = $order->getId();
								$setLinks[] = "<a href='" . $this->getUrl('sales/order/view', ['order_id' => $id]) . "'>" . $getIncrIds[$i] . "</a>";
							}
							echo '<span>' . implode(",", $setLinks) . '</span>';
						} else {
							echo '<span>N/A</span>';
						}
						?>
					</td>
				</tr>
				<tr>
					<td style="padding:5px;"><strong><?php echo __('Stock Received Id(s):'); ?></strong></td>
					<td><?php   if (!empty($srIncrIdArr[0])) {
						echo '<span>' . $srIncrIdArr[0] . '</span>';
					} else {
						echo '<span>N/A</span>';
					}?></td>
				</tr>
				<tr>
					<td style="padding:5px;"><strong><?php echo __('Invoice ID:'); ?></strong></td>
					<td><?php
						if (!empty($invoiceIdArr)) {
							echo '<span>' . $invoiceIdArr . '</span>';
						} else {
							echo '<span>N/A</span>';
						}
						?></td>
					</tr>
					<tr>
						<td style="padding:5px;"><strong><?php echo __('Required Date:'); ?></strong></td>
						<td><?php if($poData['required_date'] == '0000-00-00 00:00:00') echo "N/A"; else echo date("M d, Y",strtotime(__($poData['required_date']))); ?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</section>
<section class="admin__page-section">
	<div class="admin__page-section-content">
		<div class="admin__page-section-title">
			<h4 class="title"> <?php echo __('P.O. Comment History') ?> </h4>
		</div>
	</div>
	<div class="admin__control-table-wrapper">
		<table cellspacing="0" class="admin__control-table data-table" width="100%" 
		style="border: 1px solid #444; border-radius:0; ">
		<tbody>
			<tr>
				<td>
					<?php
					if(!empty($poCommentsCol)) 
					{
						for($i=0;$i<count($poCommentsCol);$i++)
						{
							?>
							<p style="margin:0 0 10px 0; border-bottom: 1px solid #444; padding-bottom:10px;">
								<strong><?php echo date("M d, Y",strtotime(__($poCommentsCol[$i]['created_at']))); ?></strong>&nbsp;<?php echo date("h:i:s A",strtotime(__($poCommentsCol[$i]['created_at']))); ?>
								<?php echo $poCommentsCol[$i]['comment']; ?>
							</p>
							<?php }
						} else {
							echo "N/A";
						}
						?>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</section>

<section class="admin__page-section">
	<div class="admin__page-section-content">
		<div class="admin__page-section-title">
			<h4 class="title"> <?php echo __('Shipment Information') ?> </h4>
		</div>
	</div>
	<div class="admin__control-table-wrapper">
		<table cellspacing="0" class="admin__control-table data-table" width="100%" 
		style="border: 1px solid #444; border-radius:0; ">
		<tbody>
			<tr>
				<td>
					<p style="border:1px solid #444; margin:0;"><?php echo $poData['shipment_method']; ?></p>
				</td>
			</tr>
		</tbody>
	</table>
</div>
</section>
<section class="admin__page-section">
	<div class="admin__page-section-content">
		<div class="admin__page-section-title">
			<h4 class="title"> <?php echo __('Payment Information') ?> </h4>
		</div>
	</div>
	<div class="admin__control-table-wrapper">
		<table cellspacing="0" class="admin__control-table data-table" width="100%" 
		style="border: 1px solid #444; border-radius:0; ">
		<tbody>
			<tr>
				<td>
					<p style="border:1px solid #444; margin:0;"><?php echo $poData['payment_method']; ?></p>
				</td>
			</tr>
		</tbody>
	</table>
</div>
</section>

<section class="admin__page-section order-totals">
	<div class="admin__page-section-content">
		<div class="admin__page-section-title">
			<h4 class="title"> <?php echo __('Order Totals') ?> </h4>
		</div>
	</div>
	<div class="admin__page-section-item-content">
		<fieldset id="order-totals" class="admin__fieldset order-totals">
			<table class="admin__table-secondary data-table pull-right" align="right">
				<tbody>
					<tr class="row-totals">
						<td style="" class="admin__total-mark" colspan="1">
							<?php echo __('Subtotal') ?>
						</td>
						<td style="" class="admin__total-amount">
							<span class="price"
							id="sub_total"><?php echo $priceHelper->currency($poData['total'], true, true); ?></span>
						</td>
					</tr>
					<tr class="row-totals">
						<td style="" class="admin__total-mark" colspan="1">
							<strong><?php echo __('Grand Total') ?></strong>
						</td>
						<td style="" class="admin__total-amount">
							<strong><span class="price"
								id="grand_total"><?php echo $priceHelper->currency($poData['total'], true, true); ?></span></strong>
							</td>
						</tr>
					</tbody>
				</table>
			</fieldset>
		</div>
	</section>

<?php endif; ?>