<?php
/**
 * @var \Rptech\Awards\Block\Award $block
 */
$awards = $block->getAwardsCollection();

?>
<style type="text/css">
    .col-sm-3.col-xs-6.main_row {
        min-height: 405px;
    }
</style>
<?php if (!empty($awards) && $awards->getSize()) : ?>
    <h3>
        <strong><?php echo __('Awards and Recognitions') ?></strong>
    </h3>
    <p>
        <?php
        echo __('We are recipient of several prestigious accolades from reputed media houses and brands for our
outstanding business performance. These awards are testimony of our consistent growth and the
value we bring to the ICT distribution industry.')
        ?>
    </p>

    <div class="row">
        <div class="col-sm-12">
            <div class="about-text">
                <h4><?php echo __('Awards :')?></h4>
            </div>
        </div>
    </div>
    <div class="row">
        <?php foreach ($awards as $award) :?>
            <div class="col-sm-3 col-xs-6 main_row">
                <img src="<?php echo $block->getAwardMediaPath().$award->getImage()?>" alt="<?php echo __($award->getTitle()) ?>" />
                <h5><?php echo __($award->getTitle()) ?></h5>
            </div>
        <?php endforeach; ?>
        <div class="box2-clearfix"></div>
    </div>
<?php endif;?>


