<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $btnTitle = __('Add to Wishlist'); ?>
<?php //if ($_product->isSaleable()): ?>

<?php if($_product->getTypeID()=="bundle") { ?>
    
    <div class="box-tocart">
		<div class="fieldset row">
			<?php if ($block->shouldRenderQuantity()): ?>
				<div class="col-sm-6 field qty">
					<?php
					$sell_status = $_product->getResource()->getAttribute('sell_status')->getFrontend()->getValue($_product);
                                        $bundle_price = $_product->getPriceInfo()->getPrice('regular_price')->getMinimalPrice()->getValue();
                                        if ($sell_status == 'Yes' && $bundle_price > 0  && $_product->getIsSalable()) {
                                        //if ($sell_status == 'Yes') {
						?>
<!--						<label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>-->
						<div class="control">
							<input type="number"
							       name="qty"
							       min="1"
							       id="qty"
							       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
							       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
							       class="input-text form-control qty"
							       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
							       />
						</div>
					<?php } ?>
				</div>
			<?php endif; ?>
			<div class="col-sm-6 actions product-btn">
				<?php
				$sell_status = $_product->getResource()->getAttribute('sell_status')->getFrontend()->getValue($_product);
                $bundle_price = $_product->getPriceInfo()->getPrice('regular_price')->getMinimalPrice()->getValue();
                if ($sell_status == 'Yes' && $bundle_price > 0  && $_product->getIsSalable()) {
					?>
					<button type="submit"
							title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
							class="btn action primary tocart"
                            id="product-addtocart-button">
						<span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
					</button>
				<?php } else { ?>
					<span style="display: none" class="prosku"><?php echo $_product->getSku(); ?></span>
						<a class="btn btn-enq" data-value="<?php echo $_product->getIsNvidia() ?>" id="product<?= $block->escapeHtml($_product->getId()) ?>">Send Query</a>
						
				<?php } ?>
			</div>
		</div>
	</div>
    
<?php } else { ?>
	<div class="box-tocart">
		<div class="fieldset">
			<?php if ($block->shouldRenderQuantity()): ?>
				<div class="field qty">
					<?php
					$sell_status = $_product->getResource()->getAttribute('sell_status')->getFrontend()->getValue($_product);
					 if ($sell_status == 'Yes' && $_product->getFinalPrice() > 0  && $_product->getIsSalable()) {
						?>
						<label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
						<div class="control">
							<input type="number"
							       name="qty"
							       min="1"
							       id="qty"
							       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
							       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
							       class="input-text form-control qty"
							       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
							       />
						</div>
					<?php } ?>
				</div>
			<?php endif; ?>
			<div class="actions product-btn">
				<?php
				$sell_status = $_product->getResource()->getAttribute('sell_status')->getFrontend()->getValue($_product);
            	if ($sell_status == 'Yes' && $_product->getFinalPrice() > 0  && $_product->getIsSalable()) {
				?>
					<button type="submit"
							title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
							class="btn action primary tocart"
                            id="product-addtocart-button">
						<span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
					</button>
					<?php
					if($_product->getTypeID()=="configurable") {
						$_configChild = $_product->getTypeInstance()->getUsedProducts($_product);
		                foreach ($_configChild as $child) {
		                    $childProductId = $child->getId();
		                    $childProductSku = $child->getSku();
		                    $childProductSellStatus = $child->getSellStatus();
		                    $childProductSalable = $child->getIsSalable();
		                    $childProductFinalPrice = $child->getFinalPrice();
		                    //echo $childProductSku."__".$childProductSalable."__".$childProductSellStatus."__".$child->getFinalPrice()."<br>";
		                    if($childProductSalable && $childProductSellStatus && $childProductFinalPrice>0) {
		                    	echo "<button type='submit' title='"./* @escapeNotVerified */ $buttonTitle ."'";
		                    	echo "class='btn action primary tocart' id='product-addtocart-button-".$childProductId."' style='display:none;'>";
		                    	echo "<span>"./* @escapeNotVerified */ $buttonTitle . "</span>";
		                    	echo "</button>";
		                    } else {
		                    	echo "<span style='display:none;' class='prosku config_sku_child_".$childProductId."'>" . $childProductSku . "</span>";
		                    	echo "<a class='btn btn-enq' id='product".$childProductId."' style='display:none;'>Send Enquiry</a>";
		                    }
		                }
					}
					echo $block->getChildHtml('', true);
				} else { ?>
					<span style="display: none" class="prosku"><?php echo $_product->getSku(); ?></span>
					<?php //echo "Not Available For Online Sales, Please Send Us Enquiry"; ?>
						<a class="btn btn-enq" data-value="<?php echo $_product->getIsNvidia() ?>" id="product<?= $block->escapeHtml($_product->getId()) ?>" data-isdgx="<?= array_intersect([535], $_product->getCategoryIds()) ? 1 : 0?>">Send Query</a>
				<?php
				}

				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$customerSession = $objectManager->get('Magento\Customer\Model\Session');
				$action = '';
				if($customerSession->isLoggedIn()) {
				   $action = "data-post='"./* @noEscape */ $block->getAddToWishlistParams($_product)."'";
				} else {
					$action = "onclick=doLogin();";
				}
				?>
				<!-- <button type="button"
					data-role="add-to-links" 
					<?= $action ?>
					title="<?= /* @escapeNotVerified */ $btnTitle ?>"
					class="btn action primary towishlist"
					id="product-addtocwishlist-button">
					<span><?= /* @escapeNotVerified */ $btnTitle ?></span>
				</button> -->

			</div>
		</div>
	</div>
<?php }//endif; ?>
<script type="text/x-magento-init">
	{
        "#product_addtocart_form": {
			"Magento_Catalog/js/validate-product": {}
        }
	}
</script>
<script type="text/javascript">
	function doLogin()
	{
		jQuery(".ajax-forgot-form").css('display','none');
		jQuery(".ajax-register-form").css('display','none');
		jQuery(".error1").css('display','none');
		jQuery(".ajax-login-form").css('display','block');
		jQuery(".loginotpmobbtn").val("Send OTP");
		jQuery(".loginotpverify").css('display','none');
		jQuery("#forgotmob").removeAttr("readonly")
	}
</script>
