<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$queryName = $this->getQueryText();
$_productCollection = $block->getLoadedProductCollection();
//echo "<pre>";print_r($_productCollection->getData());
//echo $block->getProdCount();echo "<br/>";
//echo "<pre>";print_r($_productCollection->getData());
//echo $_productCollection->count();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
$catalogHelperData = $this->helper('Magento\Catalog\Helper\Data');
$categoryObject = $catalogHelperData->getCategory();
$categoryId = $categoryObject->getId();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else:
    ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="col-lg-9 col-md-9 products-wrapper">
        <div class="col-xs-12 title-wrapper clearfix">
            <div class="mb-filter">
                <button class="btn"><i class="fa fa-filter"></i> Filter</button>
            </div> 

            <h3 class="title"><?php //echo $this->getLayer()->getCurrentCategory()->getName()   ?></h3>

            <div class="custom-select-my floater-left">
                <?= $block->getToolbarHtml() ?>
            </div>

        </div>
        <div class="products-row equalheight_wrapper clearfix">
			<?php //echo $_productCollection->getSelect()->__toString(); exit;?>
            <?php foreach ($_productCollection as $_product): ?>
                <div class="col-md-4 col-sm-4 col-xs-6 product-box">
                    <div class="product-inner-box product<?= $block->escapeHtml($_product->getId()) ?>">
                        <div class="txt-content">
                            <div class="proBox equalheight">
                                <div class="proBoxInner">
                                    <div class="imgDiv">
                                        <div class="img-box">
                                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product-thumbnail" target="_blank">
                                                <img class="product-img img-responsive" src="<?= $block->getImage($_product, $image)->getImageUrl(); ?>">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="proInfoDiv">
                                        <h3 class="product-title">
                                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" target="_blank">
                                                <?php 
                                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
											   echo $_productNameStripped;
                                                /* if(strlen($_productNameStripped) > 25){
                                                    echo substr($_productNameStripped, 0, 25).'...';
                                                }else{
                                                    echo $_productNameStripped;
                                                } */
                                                ?>
                                            </a>
                                        </h3>
                                        <div class="product-desc">
                                            <?php 
                                                $_productDescStripped = $_product->getShortDescription();
                                                if(strlen($_productDescStripped) > 100){
                                                    echo substr($_productDescStripped, 0, 100).'...';
                                                }else{
                                                    echo $_productDescStripped;
                                                }
                                                ?>      
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="industry">
                            <?php $industryName  = $_product->getAttributeText('industries');
                            echo $industryName;
                            ?>
                        </div>
						<div class="location">
							<?php $locationName = $_product->getResource()->getAttribute('location')->getFrontend()->getValue($_product);
							echo $locationName; ?>
						</div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php echo $block->getToolbarHtml() ?>
    </div>
    
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
            "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
            }
            }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>