<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<section class="products-section">
	<div class="container-fluid">
		<div class="row">
			<?php $catName = $block->getCurrentCategory()->getName(); ?>
			<?php if (!$block->isContentMode() || $block->isMixedMode()): ?>
				<?= $block->getProductListHtml() ?>
			<?php endif; ?>
		</div>
	</div>
</section>
