<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<section class="forgot-password-section">
    <div class="fp-wrapper">
        <h1 class="title">Forgot Your Password</h1>
        <div class="form-wrapper">
            <form class="form password forget"
                action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
                method="post"
                id="form-validate"
                data-mage-init='{"validation":{}}'>
              <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                  <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
                  <div class="field email required">
                      <div class="form-group">
                          <input type="email" name="email" alt="email" id="email_address" class="form-control" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                          <label for="email_address" class="input_label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                      </div>
                  </div>
                  <?= $block->getChildHtml('form_additional_info') ?>
              </fieldset>
              <div class="actions-toolbar">
                  <div class="primary btn-row">
                      <button type="submit" class="btn action text-white submit primary"><span><?= $block->escapeHtml(__('Send Reset Password Link')) ?></span></button>
                      <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
                  </div>
              </div>
            </form>
        </div>
    </div>
</section>

