<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<!--<div class="block block-customer-login">-->
<!--    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>-->

<section class="login-section">
    <div class="container"> 
        <div class="row">               
            <div class="login-wrapper">
                <div class="t-row">
                    <div class="col-left col-sm-6 col-xs-12">
                        <div class="inner-column">
                            <h1 class="title">Login into your Account </h1>
                            <form class="form form-login"
                                  action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                                  method="post"
                                  id="login-form"
                                  data-mage-init='{"validation":{}}'>
                                      <?= $block->getBlockHtml('formkey') ?>
                                <div class="form-group">
                                    <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="form-control" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                                    <label class="input_label">Username or Email</label>
                                </div>
                                <div class="form-group">
                                    <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="form-control" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                                    <label class="input_label">Password</label>
                                </div>
                                <?= $block->getChildHtml('form_additional_info') ?>
                                <div class="clearfix btn-wrapper">
                                    <div class="btn-row">
                                        <button class="btn">Sign In</button>
                                        <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a>
                                    </div>
                                </div>
                                <?php
                                $block1 = $this->getLayout()->createBlock('Magento\Customer\Block\Form\Login\Info');
                                ?>
                                <p class="txt">Don't have an account?  <a href="<?= $block1->escapeUrl($block1->getCreateAccountUrl()) ?>" class="action link"><?= $block1->escapeHtml(__('Create an Account')) ?></a></p>
                            </form>

                        </div>
                    </div>
                    <div class="col-right col-sm-6 col-xs-12">
                        <div class="inner-column">
                            <!--                                    <a href="#" class="login-options login-guest clearfix">
                                                                    <span class="icon"><i class="fa fa-user login-option-icon"></i></span>
                                                                    <span class="">Sign In with Guest</span>
                                                                </a>-->
                            <!--                            <a href="#" class="login-options login-fb clearfix">
                                                            <span class="icon"><i class="fa fa-facebook-f  login-option-icon"></i></span>
                                                            <span>Sign In with Facebook</span>
                                                        </a>-->
                            <?php
                            echo $this->getLayout()
                                    ->createBlock('Pekebyte\SocialLogin\Block\Frontend\SocialLogin')
                                    ->setTemplate('Pekebyte_SocialLogin::login/signinbuttons.phtml')
                                    ->toHtml();
                            ?>
                            <?php
                            echo $this->getLayout()
                                    ->createBlock('Pekebyte\SocialLogin\Block\Frontend\SocialLogin')
                                    ->setTemplate('Pekebyte_SocialLogin::login/scripts.phtml')
                                    ->toHtml();
                            ?>
                            <!--                            <a href="" class="login-options login-twit clearfix">
                                                            <span class="icon"><i class="fa fa-twitter login-option-icon"></i></span>
                                                            <span>Sign In with Twitter</span>
                                                        </a>
                                                        <a href="" class="login-options login-google clearfix">
                                                            <span class="icon"><i class="fa fa-google-plus login-option-icon"></i></span>
                                                            <span>Sign In with Google +</span>
                                                        </a>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
<?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
<?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>
            </fieldset>
        </form>
    </div>-->
<!--</div>-->

