<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Newsletter $block */
?>
<?= $block->getChildHtml('form_before') ?>
    <form class="form form-newsletter-manage block" action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
        
            <?= $block->getBlockHtml('formkey') ?>
            <div class="block-title"><strong><?= $block->escapeHtml(__('Subscription option')) ?></strong></div>
            <div class="block-content">
                <div class="form-group field choice">
                    <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?= $block->escapeHtmlAttr(__('General Subscription')) ?>"<?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                    <label for="subscription" class="label"><span><?= $block->escapeHtml(__('General Subscription')) ?></span></label>
                </div>
                <?php /* Extensions placeholder */ ?>
                <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
                <div class="clearfix actions-toolbar">
                    <div class="primary"><button type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="btn action save primary"><span><?= $block->escapeHtml(__('Save')) ?></span></button></div>
                    <div class="secondary"><a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a></div>
                </div>
            </div>

    </form>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.newsletter.extra2') ?>
