<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<div class="modal" id="enquiryModal">
	<div class="modal-dialog">
		<form class="modal-content animate" id="sendEnquiryForm" >
			<div class="modal-header">
				<span class="close" title="Close Modal"><i class="fa fa-close"></i></span>
				<h1 class="title">Enquiry for Product: <span id="proName"></span></h1>
			</div>
			<div class="modal-body">
                                <span class="error" style="display: none;">There is some error. Please try again later.</span>
                                <span class="success" style="display: none;">Your Enquiry Have been posted. We'll get back to you shortly</span>
				<div class="form-group">
					<label class="input_label">Your Name</label>
					<input type="hidden" id="baseUrl" value="<?php echo $this->getBaseUrl() ; ?>" />
					<input type="hidden" id="product_sku" name="product_sku"  />
					<input type="hidden" id="product_name" name="product_name"  />
					<input class="form-control" type="text" name="username" required="" placeholder="Enter Your Name ">
				</div>
				<div class="form-group">
					<label class="input_label">Email Id</label>
					<input class="form-control" type="email" name="useremail" required="" placeholder="Enter Your Email ID ">
				</div>
				<div class="form-group">
					<label class="input_label">Mobile</label>
					<input class="form-control" type="mobile" name="usermobile" maxlength="10" placeholder="Enter Your Mobile No ">
				</div>
				<div class="form-group">
					<label class="input_label">City</label>
				<!-- 	<input class="form-control" type="city" name="usercity" required="" placeholder="Enter Your city ">
 -->
					<select id="city" name="usercity" class="form-control">
                                        <option value="">Select City</option>
                                        <option value="Ahmedabad" selected="selected">Ahmedabad</option>
                                                <option value="Ahmednagar">Ahmednagar</option>
                                                <option value="Amritsar">Amritsar</option> 
                                                <option value="Amravati">Amravati</option>
                                                <option value="Aurangabad">Aurangabad</option>
                                                <option value="Bangalore">Bangalore</option>
                                                <option value="Baroda">Baroda</option>
                                                <option value="Bhopal">Bhopal</option>
                                                <option value="Bubneshwar">Bubneshwar</option>
                                                <option value="Calicut">Calicut</option>
                                                <option value="Chandigarh">Chandigarh</option>
                                                <option value="Chennai">Chennai</option>
                                                <option value="Cochin">Cochin</option>
                                                <option value="Coimbatore">Coimbatore</option>
                                                <option value="Dehradun">Dehradun</option>
                                                <option value="Gaziabad">Gaziabad</option>
                                                <option value="GOA">GOA</option>
                                                <option value="Gurgaon">Gurgaon</option>
                                                <option value="Guwahati">Guwahati</option>
                                                <option value="Hubli">Hubli</option>
                                                <option value="Hyderabad">Hyderabad</option>
                                                <option value="Indore">Indore</option>
                                                <option value="Jabalpur">Jabalpur</option>
                                                <option value="Jaipur">Jaipur</option>
                                                <option value="Jammu">Jammu</option>
                                                <option value="Kolhapur">Kolhapur</option>
                                                <option value="Kolkata">Kolkata</option>
                                                <option value="Kottayam">Kottayam</option>
                                                <option value="Lucknow">Lucknow</option>
                                                <option value="Ludhiana">Ludhiana</option>
                                                <option value="Madurai">Madurai</option>
                                                <option value="Mangalore">Mangalore</option>
                                                <option value="Mumbai">Mumbai</option>
                                                <option value="Mysore">Mysore</option>
                                                <option value="Nagpur">Nagpur</option>
                                                <option value="Nashik">Nashik</option>
                                                <option value="New Delhi">New Delhi</option>
                                                <option value="Patna">Patna</option>
                                                <option value="Pondicherry">Pondicherry</option>
                                                <option value="Pune">Pune</option>
                                                <option value="Raipur">Raipur</option>
                                                <option value="Rajkot">Rajkot</option>
                                                <option value="Ranchi">Ranchi</option>
                                                <option value="Sangli">Sangli</option>
                                                <option value="Siliguri">Siliguri</option>
                                                <option value="Surat">Surat</option>
                                                <option value="Trivandram">Trivandram</option>
                                                <option value="Vijaywada">Vijaywada</option>
                                                <option value="Vishkhapatnam">Vishkhapatnam</option>

                                    </select>
				</div>
				<div class="form-group">
					<label class="input_label">Comment</label>
					<textarea class="form-control" type="text" name="usercomment" placeholder="Type Here"></textarea>
				</div>


				<!-- <?php 
					//echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magecomp_Mobilelogin::customer_register.phtml")->toHtml(); 
				?>
				<div class="error1" id="verifymobileerror" style="display: none">
            		<span><//?php echo __("Please Verify Mobile First.");?></span>
        		</div> -->
				<div class="form-group">
					<button class="form-button send-enq" type="submit">Send</button>
				</div>
			</div>
                        <div class="preloader">
                            <div class="loader">
                                <img src="<?php echo $this->getViewFileUrl('images/loader-1.gif'); ?>"/>
                            </div>
                        </div>
		</form>
	</div>
</div>
<!-- <script type="text/javascript">
	require(['jquery', 'jquery/ui'], function($){
		$(".send-enq").click(function(){
			if($('#mobile-mobileget').is('[readonly]') && $('#otpverify').css('display') == 'none' && $('.regi-sendotp').css('display') == 'none' ) {
				$('#verifymobileerror').css('display','none');
			} else {
				event.preventDefault();
				$('#verifymobileerror').css('display','block');
			}
		});
	});
</script> -->