<div class="banner-left">
	<div class="banner-slider"> 
		<div class="item">
			<div class="banner-img">
                                <img src="<?php echo $this->getViewFileUrl('images/banner-img1.png') ?>">
			</div>
			<div class="banner-text">
                                <h2 class="heading text-uppercase">Beats
					<span class="text-capitalize">STRIX DSP Gaming Headphone Black - U</span></h2>
			</div>
		</div>
		<div class="item">
			<div class="banner-img">
                                <img src="<?php echo $this->getViewFileUrl('images/banner-img1.png') ?>">
			</div>
			<div class="banner-text">
                                <h2 class="heading text-uppercase">Beats
					<span class="text-capitalize">STRIX DSP Gaming Headphone Black - U</span></h2>
			</div>
		</div>
		<div class="item">
			<div class="banner-img">
                                <img src="<?php echo $this->getViewFileUrl('images/banner-img1.png') ?>">
			</div>
			<div class="banner-text">
                                <h2 class="heading text-uppercase">Beats
					<span class="text-capitalize">STRIX DSP Gaming Headphone Black - U</span></h2>
			</div>
		</div>
		<div class="item">
			<div class="banner-img">
                                <img src="<?php echo $this->getViewFileUrl('images/banner-img1.png') ?>">
			</div>
			<div class="banner-text">
                                <h2 class="heading text-uppercase">Beats
					<span class="text-capitalize">STRIX DSP Gaming Headphone Black - U</span></h2>
			</div>
		</div>
	</div>
</div>
<div class="banner-right">
	<div class="product">
		<div class="product-slider">
			<img src="<?php echo $this->getViewFileUrl('images/product-img3.png') ?>">
		</div>
		<div class="product-slider">
			<img src="<?php echo $this->getViewFileUrl('images/product-img2.png') ?>">
		</div>
	</div>
</div>
<div class="clearfix"></div>