<style type="text/css">
    @media only screen and (max-width: 768px) {
        .contactus-wapper {
            padding: 0 !important;
        }
        .contactus-wapper .tab-head{
            display: flex!important;
            flex-wrap: wrap!important;
        }
        .contactus-wapper .tab-head li a {
            font-size: 1.3em !important;
        }
        #location .contact-info {
            width: 100%!important;
        }
        #location .map {
            width: 100%;
            position: relative;
            padding: 0;
        }
        .contact-info ul li {
            margin: 0 5px!important;
        }
        .select-address{
            text-align:center;
        }
        .tab-content .heading {
            padding-bottom: 1em;
        }
        .contactus-wapper .tab-head li a {
            font-size: 16px !important;
        }
        .contactus-wapper .tab-head li {
            padding: 5px 30px !important;
        }
        .contactus-wapper .tab-head li.active:after {
            content : none !important;
        }
        .tab-content .heading {
            padding-bottom: 11px !important;
            font-size: 20px !important;
            font-weight: 400 !important;
        }

        .input .form-control:focus+.input__label {
            /*display: none !important;*/
        }
        .foot-menu {
            margin-top: 16px !important;
        }
        footer ul li a, footer .foot-copyright p {
            font-size: 12px !important;
            font-weight: 500 !important;
        }
        footer ul li a .icon-right-arrow {
            font-size: 12px !important;
        }
        footer .address ul li a, footer .address ul li address, footer .address ul li .mb-number {
            font-size: 12px !important;
        }
    }

    @media (max-width:992px) {
    
        .customer-services p {
            padding: 10px;
            height: 126px;
            margin-left: 0;
            margin-right: 0;
        }
    
    }


    /* .menu.navbar-nav.nav .dropdown-menu-large {    min-width: 290px !important; left: 0; padding: .5em; } */

    .menu.navbar-nav.nav .dropdown-menu-large {
        min-width: 600px !important;
        left: 0;
        padding: 0.5em;
    }

    @media (min-width: 768px) {
        .col-sm-6-rpt {
            width: 33%;
        }
    }

    .menu.navbar-nav.nav .dropdown-menu-large>li {
        padding-left: 0;
        padding-right: 0;
        margin-bottom: .25em;
    }

    .menu.navbar-nav.nav .dropdown-menu-large>li>a {
        color: #222;
    }

    .menu.navbar-nav.nav .dropdown-menu-large .submenu {
        min-width: 200px;
        top: 0;
        left: 100%;
    }

    .menu .dropdown-menu {
        padding: 6px 0;
        border-radius: 0;
    }

    .menu.navbar-nav.nav .dropdown-menu-large .caret-right {
        transform: rotate(-90deg);
        margin: 0 2px 2px;
    }


    /* Header End */


    /* Banner Set */

    .banner {
        background: #ebeae8 url(https://rptechindia.com/media/assets/images/head-bg.jpg) no-repeat top center;
        background-size: cover;
        padding: 6em 0 7.5em;
    }

    .banner-wrap {
        margin-top: 2.5em;
        z-index: 3;
        position: relative;
    }

    .banner .banner-slider {
        z-index: 1;
    }

    .banner .banner-slider .banner-text {
        display: table-cell;
        vertical-align: top;
        width: 50%;
        padding-left: 2.813em;
    }


    /*.banner .banner-slider .banner-text .banner-btn     { background:transparent; color:#fff; padding:8px 43px; font-size:18px; margin:0 auto; display:block;}*/

    .banner .banner-slider .banner-text .banner-btn {
        background: transparent;
        color: #fff;
        padding: 0px 0px;
        font-size: 1em;
    }

    .banner-slider .banner-text .banner-heading {
        font-size: 2.75em;
        color: #fff;
        max-width: 460px;
        margin-top: 1em;
        margin-bottom: 1rem;
    }

    .banner .banner-slider .banner-img {
        display: table-cell;
        vertical-align: middle;
        width: 50%;
    }

    .banner .slick-dots {
        z-index: 1;
        bottom: 90px;
    }

    .slick-dots li {
        height: 14px;
        width: 14px;
        margin: 0 2px;
    }

    .banner .slick-dots li button {
        height: 14px;
        width: 14px;
    }

    .banner .slick-dots li button:before {
        font-size: 0px;
        height: 14px;
        width: 14px;
        background: #fff;
        border-radius: 50%;
        margin: 0 2px;
        opacity: .5;
    }

    .banner .slick-dots li.slick-active button:before {
        opacity: 1;
    }


    /* Banner End */


    /* Main */

    .home-page .main {
        position: relative;
        margin-top: -220px;
        z-index: 1;
    }

    .main {
        background: #fff;
        position: relative;
        z-index: 1;
    }


    /*Who We Are*/

    .who-we-are {
        padding: 0 3.438em 2.813em 3.438em;
        display: block;
    }

    .who-we-are .heading {
        font-size: 3.750em;
        color: #080b12;
        font-weight: 300;
        padding: 120px 0 25px 0;
        margin: 0px;
    }

    .who-we-are .heading span {
        font-weight: 500;
    }

    .who-we-are p {
        line-height: 1.625em;
        color: #383838;
        padding-bottom: 2.00em;
        margin: 0px;
    }

    .who-we-are .view-btn {
        padding: 0.389em 1.667em;
        color: #fff;
        font-size: 1.125em;
        background-color: #848484;
    }


    /*Who We Are*/


    /*Latest Section */

    .letest-sec {
        background: #6d2a88;
        position: relative;
        margin-top: 2.813em;
        margin-bottom: 5.313em;
        padding-top: 30px;
        height: 830px;
    }

    .letest-sec .heading {
        font-weight: 300;
        color: #fff;
    }

    .letest-sec .letest-sec-left .heading {
        margin: 1.042em 0;
    }

    .letest-sec .letest-sec-left {
        color: #fff;
        padding: 0 0 0 2.813em;
        width: calc(100% - 490px);
    }

    .letest-sec-left .heading strong {
        display: block;
    }

    .letest-sec-left ul li {
        position: relative;
        margin: 0 0 1.250em 0;
    }


    /*.letest-sec-left ul li:before			 	{ content:"\f105"; font-family:fontawesome; background:#fff; padding:2px 5px; color:#5c5c5c;}*/

    .letest-sec-left ul li i.fa {
        background: #fff;
        padding: 0px 4px;
        color: #3a3939;
        display: inline-block;
        vertical-align: top;
    }

    .letest-sec-left ul li span {
        width: calc(100% - 35px);
        font-size: 14px;
        display: inline-block;
        vertical-align: top;
        padding-left: 1.250em;
        margin-top: -3px;
    }

    .letest-sec-left .btn {
        color: #522664;
        margin: 1.625em 0 3.125em 0;
        border-radius: 360px;
        padding: 0.375em 1.438em;
        transition: .5s;
    }

    .letest-sec-left .btn:hover {
        color: inherit;
    }

    .letest-sec .letest-sec-right {
        background: #522664;
        position: absolute;
        margin-top: -3.750em;
        top: 0;
        bottom: 0;
        right: 0;
        padding: 0 1.438em;
        color: #fff;
        width: 490px;
    }

    .letest-sec .letest-sec-right .heading {
        margin: 0.833em 0 0.625em 0;
    }

    .offer-details {
        width: 100%;
        display: block;
        margin-bottom: 16px;
    }

    .offer-details .box {
        background: #848484;
        display: table;
        width: 100%;
        border-radius: 7px;
        position: relative;
        transition: 0.5s;
    }

    .offer-details .details-icon {
        width: 100px;
        position: absolute;
        font-size: 3.750em;
        color: #fff;
        background: #b6b4b4;
        text-align: center;
        border-top-left-radius: 7px;
        border-bottom-left-radius: 7px;
        left: 0;
        top: 0;
        bottom: 0;
    }

    .details-icon span:before {
        position: absolute;
        left: 0;
        right: 0;
        top: 50%;
        margin-top: -30px;
    }

    .offer-details span {
        vertical-align: middle;
        margin-top: 29px;
        display: block;
    }

    .offer-details .details-contant {
        background: #848484;
        vertical-align: middle;
        border-bottom-right-radius: 7px;
        border-top-right-radius: 7px;
        color: #fff;
        width: calc(100% - 100px);
        padding: 2.183em 0 2.183em 1.00em;
        margin-left: 100px;
    }

    .offer-details .details-contant span {
        display: table-cell;
        width: 95%;
        vertical-align: middle;
        font-size: 1.375em;
        position: relative;
        left: 0;
        transition: 0.5s all ease;
    }

    .offer-details .details-contant .get-offer {
        display: table-cell;
        color: #fff;
        vertical-align: middle;
        padding-left: 0;
        width: 5%;
        padding-right: 10px;
    }

    .details-contant .get-offer .btn {
        border-radius: 30px;
        padding: 0.250em 1.25em;
        color: #fff;
    }

    .details-contant .get-offer .btn:hover {
        color: inherit;
    }

    .offer-details a:hover {
        color: rgba(255, 255, 255, 0.8);
    }

    .offer-details a:hover .details-contant {
        color: rgba(255, 255, 255, 0.8);
    }

    .offer-details .details-contant .get-offer span {
        transition: 0.5s;
    }

    .offer-details .box:hover .details-contant .get-offer span {
        left: 0.250em;
    }


    /*Latest Section */


    /*Aur brand Section */

    .aur-brand {
        padding: 0 1.875em 4.688em 1.875em;
    }

    .aur-brand .heading {
        border-bottom: solid 1px rgba(130, 130, 130, 0.34);
        font-weight: 300;
        padding-bottom: 0.417em;
    }

    .aur-brand ul li {
        width: 12%;
        float: left;
        margin: 1.250em 0;
    }

    .aur-brand ul li a {
        border: solid 1px rgba(130, 130, 130, 0.18);
        transition: .5s;
        border-radius: 6px;
        display: block;
        margin: 0 0.500em;
        padding: 0.625em 0;
    }

    .aur-brand ul li a img {
        transform: scale(0.85);
        transition: 0.5s;
    }

    .aur-brand ul li a:hover {
        box-shadow: 0 0 10px rgba(187, 187, 187, 0.5);
    }

    .aur-brand ul li a:hover img {
        transform: scale(1);
    }


    /*Home brand Section */

    .brand-horz-list {
        position: relative;
        border: solid 1px rgba(130, 130, 130, 0.18);
        border-radius: 10px;
        margin: 5px;
        margin-bottom: 30px;
        padding: 6px;
        display: inline-block;
        max-width: 125px;
    }

    .brand-horz-list-img {
        max-width: 100%;
        max-height: 100%;
        display: inline-block;
    }


    /* .brand-horz-list:hover{
        transform: scale(0.5);
      } */


    /*Inner Header*/

    .inner-header {
        position: relative;
        top: 0;
        z-index: 2;
        transition: all 0.4s ease;
    }

    .inner-header.fixed-header {
        position: fixed;
        top: 0;
        left: 0;
        z-index: 2;
        width: 100%;
    }

    .inner-header .lists {
        font-weight: normal;
        color: black;
    }

    .inner-header .dropdown a {
        text-decoration: none;
        color: black;
    }

    .inner-header .navbar {
        background-color: #fff;
        padding: 2px;
        margin-bottom: 0;
        box-shadow: 3px 0px 2px 2px #dedcdc;
        border-top: solid 0px #a02a7e;
    }

    .inner-header .navbar-default-1 .navbar-nav>li>a {
        color: black;
        font-weight: normal;
    }

    .inner-header .nav-logo .navbar-brand {
        padding: 0;
        max-width: 120px;
        margin-left: 0;
    }

    .inner-header .caret-1 {
        display: inline-block;
        width: 0;
        height: 0;
        margin-left: 2px;
        vertical-align: middle;
        border-top: 4px dashed;
        border-top: 4px solid\9;
        border-right: 4px solid transparent;
        border-left: 4px solid transparent;
    }

    .inner-header .mi1 {
        margin-left: 17px;
    }

    .inner-header .navbar-header {
        position: relative;
    }

    .inner-header .ico {}

    .inner-header .icon1 {
        height: 11px;
    }

    .inner-header li.header-icon.lists {}

    .inner-header .menu.navbar-nav>li.active a,
    .inner-header .menu.navbar-nav>li>a:hover,
    .inner-header .menu.navbar-nav>li>a:focus {
        background-color: transparent;
        color: #000 !important;
    }

    .main-inner .inner-wrapper {
        border-bottom-left-radius: 20px;
        border-bottom-right-radius: 20px;
    }

    .main-container.pt {
        padding-top: 100px;
    }


    /*About*/

    .about-wapper {
        padding: 0px 30px;
        background-color: #fff;
    }

    .about-content {}

    .about-wapper h5 {
        font-size: 17px;
        text-align: center;
        min-height: 75px;
    }

    .about-wapper .text-line {
        font-size: 14px;
        color: #6a6868;
    }

    .about-content h3 {
        font-size: 1.875em;
        font-weight: bold;
        padding-bottom: 20px;
        margin-top: 0;
    }

    .about-content p {
        font-size: 14px;
        padding-bottom: 22px;
    }

    .about-text h4 {
        font-size: 1.500em;
        font-weight: bold;
    }

    .about-text p {
        font-size: 14px;
        margin-top: 16px;
    }

    ul {
        list-style: none;
    }

    .list {
        list-style-image: url(../images/icon-li.png);
    }

    .list li {
        margin: 10px 18px;
    }

    .box2-clearfix {
        height: 15px;
    }

    .box3-clearfix {
        margin-bottom: 60px;
    }

    .box3-clearfix h3 {
        font-size: 1.875em;
        font-weight: 500;
        color: #522664;
    }

    .breadcrumb {
        background-color: transparent;
    }


    /*End About*/


    /* Breadcrum */

    .breadcrumb {
        padding: 10px 0;
        margin-bottom: 0;
    }

    ul.breadcrumb {
        list-style: none;
    }

    ul.breadcrumb li {
        display: inline;
        font-size: 14px;
        color: #555555;
    }

    ul.breadcrumb li a {
        color: #522664;
        text-decoration: none;
        font-weight: bold;
    }

    ul.breadcrumb li a:hover {
        color: #522664;
        text-decoration: none;
    }

    i {
        display: inline-block;
    }

    .right {
        padding: 3px;
        margin: 1px 12px;
        border: solid black;
        border-width: 0 1px 1px 0;
        transform: rotate(-45deg);
        -webkit-transform: rotate(-45deg);
    }


    /* .right                                      { border-width: 0 1px 1px 0; } */

    .pull-right {
        position: relative;
        margin-top: -29px;
    }


    /* Error */

    .error-background {
        background-image: url(../images/error.jpg);
        background-repeat: no-repeat;
        width: 100%;
        height: 100%;
        background-position: left center;
        background-size: cover;
    }

    .error-background .construction-wrapper {
        max-width: 550px;
        width: 100%;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .error-background .construction-wrapper .title {
        font-size: 4.500em;
        color: #57524c;
        font-weight: 100;
    }

    .error-background .construction-wrapper .sub-title {
        font-size: 2.250em;
        color: #57524c;
        font-weight: 100;
        margin-top: -12px;
    }

    .error-background .construction-wrapper .txt {
        font-size: 1.125em;
        color: #57524c;
        font-weight: 100;
        padding: 6px 0px 14px 0px;
    }

    .error-background .construction-wrapper .txt b {
        font-size: 1.125em;
        color: #0f6ac9;
        font-weight: 500;
    }

    .error-background .construction-wrapper .txt a {
        color: #2f3474;
    }

    .error-background .construction-wrapper hr,
    .construction-page-wrapper hr {
        border-top: 1px solid #cccccc;
        margin-top: 1em;
        margin-bottom: 1em;
    }

    .error-search {
        height: 43px;
        width: 835px;
    }

    .error-search-button {
        background-color: #a02a7f;
        color: #fff;
        border: none;
    }

    .input-group-addon {
        background-color: #a02a7f;
        color: #fff;
    }


    /*End Error */


    /* News */

    .news-wapper {
        padding: 0px 30px 100px;
        background-color: #fff;
    }

    .home-page .main {
        background: #fff;
        border-bottom-left-radius: 20px;
        border-bottom-right-radius: 20px;
        position: relative;
        border-top-left-radius: 20px;
        border-top-right-radius: 20px;
    }

    .main {
        background: #fff;
        position: relative;
        border-bottom-left-radius: 20px;
        border-bottom-right-radius: 20px;
    }

    .box-news {
        float: left;
        height: 89px;
        position: relative;
        width: 50px;
    }

    .news-sub-menu {
        border-bottom: 1px solid #cac9c8;
    }

    .news-sub-menu h2 {
        font-size: 24px;
        color: #2b2b2b;
    }

    .news-sub-menu p {
        font-size: 18px;
    }

    .margin1611 {
        margin-top: 15px;
    }


    /* End News */


    /* Media */

    .media-wapper {
        padding: 0px 30px 100px;
        background-color: #fff;
    }

    .media-search {
        text-align: center;
        max-width: 150px;
        padding: 0px 10px;
        line-height: 32px;
        background-color: #a02a7f;
        color: white;
        border: 1px solid #d7d5d5;
        border-radius: 4px;
        transition: 0.5s;
    }

    .media-search .fa {
        padding-right: 10px;
    }

    #more {
        display: none;
    }

    .media-sub-menu {
        border-bottom: 1px solid #cac9c8;
        padding: 1.5em 0 .75em;
    }

    .media-sub-menu h3 {
        font-size: 14px;
        color: #a02a7f;
        font-weight: 500;
        margin: 0 0 .4em;
    }

    .media-sub-menu p {
        font-size: 16px;
        margin-bottom: 0;
    }

    .media-sub-menu .col-right {
        text-align: center;
    }

    .media-sub-menu .col-right p {
        color: #2b2b2b;
        font-size: 1.125em;
    }

    .morecontent span {
        display: none;
    }

    .morelink {
        display: inline-block;
        color: #6e2d88;
        font-size: 12px;
        text-decoration: none;
    }

    .morelink:focus {
        text-decoration: none;
        color: #6e2d88;
    }

    .morelink:hover {
        text-decoration: none;
    }

    .morelink less:hover {
        text-decoration: none;
    }

    .media-menu {
        position: relative;
    }


    /*End Media */


    /* contact us page  */

    .contactus-wapper {
        padding: 0px 30px;
        background-color: #fff;
        overflow-x: hidden;
    }

    .tab-content .heading {
        padding-bottom: 2.250em;
        font-size: 2.125em;
        font-weight: 400;
    }


    /* .contactus-wapper 						      {} */

    .contactus-wapper .tab-head {
        display: table;
        max-width: 960px;
        margin: 0 auto;
        border-bottom: solid 2px #6d2a88;
        margin-bottom: 20px;
    }

    .contactus-wapper .tab-head li {
        display: table-cell;
    }

    .contactus-wapper .tab-head li a {
        display: block;
        font-size: 1.250em;
        color: #000;
    }

    .contactus-wapper .tab-head li {
        padding: 14px 30px;
    }

    .contactus-wapper .tab-head li.active a {
        color: #6d2a88;
    }

    .contactus-wapper .tab-head li.active {
        position: relative;
    }

    .contactus-wapper .tab-head li.active:after {
        width: 10px;
        height: 10px;
        position: absolute;
        content: "";
        top: 100%;
        left: 50%;
        border-style: solid;
        border-width: 10px;
        margin-left: -10px;
        margin-top: 0;
        border-color: #6d2a88 transparent transparent;
    }

    .main_contact {
        position: relative;
    }

    .contact-info {
        width: 35%;
        min-height: 450px;
        background-color: #6d2a88;
    }

    .contact-info ul li {
        margin: 0 20px;
        padding: 15px;
        text-align: center;
    }

    .contact-info ul li a {
        color: #fff;
    }

    .contact-info ul li+li {
        border-top: solid #b6b4b4 1px;
    }

    .contact-info ul li .contact-info-icon {
        background: #a02a7e;
        border-radius: 50%;
        height: 60px;
        width: 60px;
        margin: 0 auto 15px;
        line-height: 68px;
    }

    .contact-info ul li .contact-info-text {
        margin: 0 auto 15px;
    }

    .contact-info ul li .contact-info-text .txt {
        font-size: 1rem;
    }

    .contact-info ul li .contact-info-icon i.fa {
        font-size: 30px;
    }

    .map {
        width: 65%;
        position: absolute;
        right: 0;
        top: 0;
        bottom: 0;
        padding: 0px 15px 10px 0px;
    }

    .enquiry {
        margin: 0 auto;
    }

    .enquiry_wrap {
        padding: 0 15px;
        max-width: 991px;
        margin: 60px auto;
    }

    .contactus-wapper .view-btn {
        margin: 2.813em auto 0;
        color: #ffffff;
        font-size: 1.500em;
        display: block;
        background: #522664;
        padding: 0.8em 3.5em;
    }

    .branches_wrap {
        height: 190px;
        background-image: url(https://magento-1139921-5320766.cloudwaysapps.com/media/assets/images/contact-branches-bg.jpg);
        background-repeat: no-repeat;
        background-position: top center;
    }

    .branches_wrap .branches_inner {
        max-width: 450px;
        margin: 0 auto;
        padding: 0 0 50px 0
    }

    .branches_wrap .heading {
        margin: 0 auto;
        padding: 34px 0px;
        color: #fff;
    }

    .branches_wrap .branches_inner .sel__placeholder {
        color: #fff;
    }

    .branches_wrap .branches_inner .sel {
        border-color: #fff;
    }

    .wrapper .pagination>li.active>a {
        background-color: #6e2d88;
        border-color: #6e2d88;
    }

    .opportunities_wrap {
        max-width: 991px;
        margin: 2.5em auto 3.5em;
    }

    .contactus-wapper .error {
        color: #ff3300;
        font-size: 14px;
        font-weight: normal;
        margin-top: 0;
        padding: 0;
    }

    .contactus-wapper .required_field {
        color: #ff3300;
    }




    /* ----- About Us ------*/

    .click_top {
        position: fixed;
        right: 20px;
        bottom: 20px;
        display: none;
        z-index: 9;
    }


    /*input
    =========================================*/

    .input {
        position: relative;
        overflow: hidden;
        padding-top: 0.5em;
    }

    .input .form-control {
        border: 0;
        position: absolute;
        left: 0;
        right: 0;
        bottom: 0.325em;
        color: #455a64;
        padding: 0px;
        box-shadow: none;
        background: transparent;
        z-index: 1;
    }

    .input__label {
        -moz-user-select: none;
        color: #455a64;
        padding: 0 1em;
        font-size: 1.143em;
        left: 0;
        padding: 0;
        pointer-events: none;
        position: absolute;
        bottom: 0.9em;
        transform-origin: 0 0 0;
        -moz-transform-origin: 0 0 0;
        -ms-transform-origin: 0 0 0;
        -o-transform-origin: 0 0 0;
        -webkit-transform-origin: 0 0 0;
        transition-delay: 0.25s, 0s;
        -moz-transition-delay: 0.25s, 0s;
        -ms-transition-delay: 0.25s, 0s;
        -o-transition-delay: 0.25s, 0s;
        -webkit-transition-delay: 0.25s, 0s;
        transition-duration: 0.2s, 1s;
        -moz-transition-duration: 0.2s, 1s;
        -ms-transition-duration: 0.2s, 1s;
        -o-transition-duration: 0.2s, 1s;
        -webkit-transition-duration: 0.2s, 1s;
        transition-property: transform, color;
        -moz-transition-property: transform, color;
        -ms-transition-property: transform, color;
        -o-transition-property: transform, color;
        -webkit-transition-property: transform, color;
        transition-timing-function: ease-out;
        -moz-transition-timing-function: ease-out;
        -ms-transition-timing-function: ease-out;
        -o-transition-timing-function: ease-out;
        -webkit-transition-timing-function: ease-out;
        width: 100%;
        font-weight: normal;
        -webkit-font-smoothing: subpixel-antialiased;
        margin-bottom: 0;
    }


    /*.input__label-content						{ display: block; position: relative; padding: 5px 0; }*/

    svg:not(:root) {
        overflow: hidden;
    }

    .graphic {
        pointer-events: none;
        stroke: #d8dadb;
        height: 2.813em;
        transition-delay: 0s, 0s;
        -moz-transition-delay: 0s, 0s;
        -ms-transition-delay: 0s, 0s;
        -o-transition-delay: 0s, 0s;
        -webkit-transition-delay: 0s, 0s;
        transition-duration: 0.7s, 0.7s;
        -moz-transition-duration: 0.7s, 0.7s;
        -ms-transition-duration: 0.7s, 0.7s;
        -o-transition-duration: 0.7s, 0.7s;
        -webkit-transition-duration: 0.7s, 0.7s;
        transition-property: transform, stroke;
        -moz-transition-property: transform, stroke;
        -ms-transition-property: transform, stroke;
        -o-transition-property: transform, stroke;
        -webkit-transition-property: transform, stroke;
        transition-timing-function: cubic-bezier(0, 0.25, 0.5, 1);
        -moz-transition-timing-function: cubic-bezier(0, 0.25, 0.5, 1);
        -ms-transition-timing-function: cubic-bezier(0, 0.25, 0.5, 1);
        -o-transition-timing-function: cubic-bezier(0, 0.25, 0.5, 1);
        -webkit-transition-timing-function: cubic-bezier(0, 0.25, 0.5, 1);
        fill: none;
        pointer-events: none;
        fill: none;
        -webkit-font-smoothing: subpixel-antialiased;
    }

    .input .form-control:focus+.error+.input__label,
    .input .form-control:focus+.input__label,
    .input--filled .input__label {
        transform: translate3d(0px, -1em, 0px) scale3d(0.75, 0.75, 1);
        -moz-transform: translate3d(0px, -1em, 0px) scale3d(0.75, 0.75, 1);
        -ms-transform: translate3d(0px, -1em, 0px) scale3d(0.75, 0.75, 1);
        -o-transform: translate3d(0px, -1.15em, 0px) scale3d(0.75, 0.75, 1);
        -webkit-transform: translate3d(0px, -1em, 0px) scale3d(0.75, 0.75, 1);
        color: #455a64;
        -webkit-font-smoothing: subpixel-antialiased;
    }

    .input .form-control:focus~.graphic,
    .input--filled .graphic {
        transform: translate3d(-66.6%, 0px, 0px);
        -moz-transform: translate3d(-66.6%, 0px, 0px);
        -ms-transform: translate3d(-66.6%, 0px, 0px);
        -o-transform: translate3d(-66.6%, 0px, 0px);
        -webkit-transform: translate3d(-66.6%, 0px, 0px);
        stroke: #d8dadb;
        /*#00b8d3*/
    }

    .input .form-control:focus+.input__label {
        transform: none;
    }
    .input__label {
        position: unset;
    }

    /*input
    =========================================*/


    /*select
    =========================================*/

    .sel {
        font-size: 1rem;
        display: inline-block;
        width: 100%;
        background-color: transparent;
        position: relative;
        cursor: pointer;
    }

    .sel__placeholder {
        font-size: 1.143em;
        display: block;
        color: #455a64;
        padding-bottom: .5em;
        text-align: left;
        pointer-events: none;
        user-select: none;
        visibility: visible;
    }

    .sel.active .sel__placeholder {
        visibility: hidden;
    }

    .sel__placeholder::after {
        position: absolute;
        top: 50%;
        right: 0;
        margin-top: -8px;
        content: "\f107";
        font-family: fontawesome;
        visibility: visible;
        transition: 0.5s;
        font-weight: bold;
    }

    .sel.sel--black-panther.active .sel__placeholder::after {
        transform: rotate(180deg);
        visibility: visible;
        transition: 0.5s;
        font-weight: bold;
    }

    .sel__placeholder::before {
        position: absolute;
        left: 0;
        right: 0;
        content: attr(data-placeholder);
        visibility: hidden;
    }

    .sel.active .sel__placeholder::before {
        visibility: visible;
    }

    .sel__box {
        position: absolute;
        top: calc(100% + 4px);
        left: -4px;
        display: none;
        list-style-type: none;
        text-align: left;
        font-size: 1em;
        background-color: #FFF;
        width: calc(100% + 8px);
        box-sizing: border-box;
    }

    .sel.active .sel__box {
        z-index: 3;
        background-color: #fff;
        display: block;
        animation: fadeInUp 500ms;
        max-height: 200px;
        overflow-y: auto;
    }

    .sel__box__options {
        display: block;
        padding: 10px;
    }


    /* ----- Select Box Black Panther ----- */

    .sel {
        border-bottom: 1px solid rgba(69, 90, 100, 0.2);
    }

    .sel--black-panther {
        padding-top: 0.4em;
        margin-top: .4em;
    }


    /* ----- Select Box Superman ----- */

    .sel--superman {
        z-index: 2;
    }


    /* ===== Keyframes ===== */

    @keyframes fadeInUp {
        from {
            opacity: 0;
            transform: translate3d(0, 20px, 0);
        }
        to {
            opacity: 1;
            transform: none;
        }
    }

    @keyframes fadeOut {
        from {
            opacity: 1;
        }
        to {
            opacity: 0;
        }
    }

    .custom-file label {
        font-weight: normal;
        color: #455a64;
        font-size: 1.143em;
    }

    .file {
        position: relative;
    }

    .custom-file .browse_btn input[type="file"] {
        position: absolute;
        left: 0;
        opacity: 0;
        top: 0;
        bottom: 0;
        width: 100%;
    }

    .custom-file .browse_btn div {
        position: absolute;
        left: 0;
        top: 0;
        bottom: 0;
        width: 100%;
        text-align: center;
        line-height: 40px;
    }

    .custom-file .browse_btn {
        background: #2f3474;
        display: inline-block;
        float: left;
        margin-bottom: 0;
        position: relative;
        height: 42px;
        width: 140px;
        color: #fff;
        font-weight: 400;
        font-size: 18px;
    }

    .custom-file .browse_btn div.dragover {
        box-shadow: 0 0 10px #aaa;
    }

    .custom-file .file .file_path {
        display: inline-block;
        margin-top: .75em;
        padding-left: 5px;
    }

    .contactus-wapper textarea.form-control {
        height: 40px;
        padding-top: .5em;
    }


    .contactus-wapper .tab-head li a {
        font-size: 1.6em;
    }

    .contact-info ul li .contact-info-text .txt {
        font-size: 1.25em;
        color: #FFF;
    }
</style>