<?php

$poModel = $block->getPurchaseOrder();
$poID = $this->getRequest()->getParam('po_id');
$poCollection = $poModel->load($poID);
$poData = $poCollection->getData();
$poCommentsCol = $poModel->getComments($poCollection);
?>

<div class="admin__page-section-item-title">
	<span class="title"><?php echo __('PO Comment History') ?></span>
</div>
<div id="po_history_block" class="admin__page-section-item-content edit-order-comments">
	<div class="order-history-block">
		<div class="admin__field">
			<label for="po_comment" class="admin__field-label"><?php echo __('Comment') ?></label>

			<div class="admin__field-control">
				<textarea type="text" rows="3" cols="5" id="po_comment" class="admin__control-textarea"
				name="po_comment"></textarea>
			</div>
		</div>
		<div class="admin__field">
			<div class="order-history-comments-actions">
				<?php echo $block->getChildHtml('submit_button') ?>
			</div>
		</div>
	</div>
	<ul class="note-list">
		<?php for ($i = 0; $i < count($poCommentsCol); $i++) {
			?>
			<li class="note-list-item">
				<span class="note-list-date"><?php echo date("M d, Y", strtotime(__($poCommentsCol[$i]['created_at']))); ?></span>
				<span class="note-list-time"><?php echo date("h:i:s A", strtotime(__($poCommentsCol[$i]['created_at']))); ?></span>

				<div class="note-list-comment"><?php echo $poCommentsCol[$i]['comment']; ?></div>
			</li>
			<?php
		} ?>
	</ul>
</div>
