<?php
$collection = $block->getProductCollection();
?>
<div class="my-account">
    <div class="page-title">
        <h1>My Orders</h1>
    </div>
    <?php echo $block->getPagerHtml(); ?>
    <?php if (count($collection) > 0): ?>
        <table id="my-orders-table" class="data-table">
            <colgroup><col width="1">
                <col width="1">
                <col>
                <col width="1">
                <col width="1">
                <col width="1">
            </colgroup>
            <?php
            $poStatus = "";
            ?>    
            <thead>
                <tr class="first last">
                    <th width="30%">Order #</th>
                    <th width="25%">Date</th>
                    <th width="15%"><span class="nobr">Order Total</span></th>
                    <th width="15%">Status</th>
                    <th width="15%">Action</th>
                </tr>
            </thead>
            <tbody>

                <?php $oddEven = 1; ?>
                <?php foreach ($collection as $poData) {
                    ?>
                    <?php if ($oddEven == 1) {
                        ?>
                        <tr class="first odd">
                        <?php } else if ($oddEven % 2 == 0) {
                            ?>
                        <tr class="even">
                            <?php
                        } else {
                            ?>
                        <tr class="odd">
                            <?php
                        }
                        ?>
                        <td width="30%"><?php echo $poData->getPurchaseOrderId() ?></td>
                        <td width="25%"><?php echo date("d/m/Y", strtotime($poData->getCreatedAt())); ?></td>
                        <td width="15%"><?php echo "$" . $poData->getTotal() ?></td>
                        <td width="15%"><i><?php echo ucwords($poData->getStatus()) ?></i></td>
                        <td width="15%"><a href="<?php echo $this->getUrl('inventorysystem/supplierorder/vieworderdetails', array('id' => $poData->getId())); ?>">View Order</a></td>
                    </tr>
                    <?php
                    $oddEven++;
                }
                ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('my-custom-table');</script>
        <?php echo $block->getPagerHtml(); ?>
    <?php else: ?>
        <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have placed no orders.'); ?></span></div>
            <?php endif ?>
</div>