<?php
$poID = $this->getRequest()->getParam('id');
$poCollection = $block->getPO()->load($poID);
$poiCollection = $block->getPOItem()->getCollection()->addFieldToFilter('purchase_order_id', $poID);
$poCommentsCol =  $block->getPOComment()->getCollection()->addFieldToFilter('purchaseorder_id', $poID)->setOrder('created_at', 'DESC')->getData();;

$poData = $poCollection->getData();
$poiData = $poiCollection->getData();

$resource =  $block->getResourceConnection();

$readConnection = $resource->getConnection();
$sql = "SELECT GROUP_CONCAT(stockreceived_id) AS stockreceived_id FROM " . $resource->getTableName('bc_stockreceived_is') ." WHERE purchaseorder_id = '" . $poData['purchase_order_id'] . "'";
$srIncrIdArr = $readConnection->fetchCol($sql);

$supCollection = $block->getSupplier()->load($poID);
$supName = $supCollection->getFirstName() . " " . $supCollection->getLastName();

$storeManager = $block->getStore();
$currency_code = $storeManager->getStore()->getCurrentCurrency()->getCode();

$storeManager = $block->getPriceCurrency();
$currency_symbol = $storeManager->getCurrency()->getCurrencySymbol();
?>
<div class="page-title title-buttons">
    <h1><?php echo __($poData['purchase_order_id']) . " | " . date("M d, Y h:i:s A", strtotime(__($poData['created_at']))); ?></h1>
</div>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2>Shipment Information</h2>
            </div>
            <div class="box-content">
                <?php echo $poData['shipment_method']; ?>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h2>Payment Information</h2>
            </div>
            <div class="box-content">
                <?php echo $poData['payment_method']; ?>
            </div>
        </div>
    </div>
</div>
<div class='order-items order-details'>
    <h4 class='table-caption'><?php echo __('Purchase Order Items'); ?> </h4>
    <table cellspacing="0" class="data-table" width="100%">
        <thead>
            <tr class="first last">
                <th width="35%"><?php echo __('Name'); ?></th>
                <th width="35%"><?php echo __('SKU'); ?></th>
                <th width="10%"><?php echo __('Quantity Purchased'); ?></th>
                <th width="10%"><?php echo __('Quantity Received'); ?></th>
                <th width="10%"><?php echo __('Unit Cost'); ?></th>
                <th width="10%"><?php echo __('Row Total'); ?></th>
            </tr>
        </thead>
        <tbody class="odd">
            <?php
            for ($i = 0; $i < count($poiData); $i++) {
                ?>
                <tr>
                    <td width="35%"><?php echo $poiData[$i]['product_name']; ?></td>
                    <td width="35%"><?php echo $poiData[$i]['product_sku']; ?></td>
                    <td width="10%"><?php echo $poiData[$i]['qty_purchased']; ?></td>
                    <td width="10%"><?php
                        if ($poiData[$i]['qty_received'] == '')
                            echo 0;
                        else
                            echo $poiData[$i]['qty_received'];
                        ?></td>
                    <td width="10%"><?php echo $currency_symbol . number_format($poiData[$i]['cost'], 2); ?></td>
                    <td width="10%"><?php echo $currency_symbol . number_format($poiData[$i]['row_total'], 2); ?></td>
                </tr>
                <?php
            }
            ?>
        </tbody>
        <tfoot>
            <tr class="grand_total last">
                <td class="a-right" colspan="5"> Subtotal </td>
                <td class="last a-right">
                    <span class="price" id="sub_total"><?php echo $currency_symbol . number_format($poData['total'], 2); ?></span>
                </td>
            </tr>
            <tr class="subtotal first">
                <td class="a-right" colspan="5"><strong>Grand Total</strong></td>
                <td class="last a-right">
                    <strong>
                        <span class="price" id="grand_total"><?php echo $currency_symbol . number_format($poData['total'], 2); ?></span>
                    </strong>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<br>
<div class="col2-set order-info-box">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo __('Additional Details'); ?></h4>
        </div>
        <fieldset>
            <div>
                <div>
                    <table>
                        <tr>
                            <td><strong><?php echo __('Supplier: '); ?></strong>&nbsp;&nbsp;</td>
                            <td><?php echo $supName; ?></td>
                        </tr>
                        <?php
                        $poStatuses = "";
                        //$poStatuses = Mage::getSingleton('inventorysystem/purchaseorders_status')->getPOStatusArray()
                        ?>
                        <tr>
                            <td><strong><?php echo __('PO Status: '); ?></strong></td>
                            <td><?php echo ucwords($poData['status']); ?></td>
                        </tr>
                        <tr>
                            <td><strong><?php echo __('Sales Order(s): '); ?></strong></td>
                            <td><?php
                                if ($poData['sales_order_id']) {
                                    //echo $poData['sales_order_id'];
                                    $getIncrIds = explode(",", $poData['sales_order_id']);
                                    for ($i = 0; $i < count($getIncrIds); $i++) {

                                        $order = $block->getOrder()->load($getIncrIds[$i], 'increment_id');
                                        //$order = Mage::getModel('sales/order')->load($getIncrIds[$i], 'increment_id');
                                        $id = $order->getId();
                                        $setLinks[] = "<a target='_blank' href='" . $block->getUrl('adminhtml/sales_order/view', array('order_id' => $id)) . "'>" . $getIncrIds[$i] . "</a>";
                                    }
                                    echo implode(",", $setLinks);
                                } else {
                                    echo "N/A";
                                }
                                ?></td>
                        </tr>
                        <tr>
                            <td><strong><?php echo __('Stock Received ID(s): '); ?></strong></td>
                            <td><?php
                                    echo "N/A";
                                ?></td>
                        </tr>
                        <tr>
                            <td><strong><?php echo __('Invoice ID: '); ?></strong></td>
                            <td><?php
                                $invSql = "SELECT id,invoice_incr_id
                                                  FROM " . $resource->getTableName('bc_purchaseinvoice_is') .
                                        " WHERE purchase_order_id = '" . $poData['purchase_order_id'] . "'";
                                $invIncrId = $readConnection->fetchAll($invSql);
                                if ($invIncrId && !empty($invIncrId)) {
                                    ?>
                                    <a target="_blank" href="<?php echo $block->getUrl('adminhtml/purchaseinvoice/view', array('id' => $invIncrId[0]['id'])); ?>"><?php echo $invIncrId[0]['invoice_incr_id']; ?></a>
                                    <?php
                                } else {
                                    echo "N/A";
                                }
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td><strong><?php echo __('Required Date: '); ?></strong></td>
                            <td><?php
                                if ($poData['required_date'] == '0000-00-00 00:00:00' || $poData['required_date'] == '1970-01-01 00:00:00')
                                    echo "N/A";
                                else
                                    echo date("M d, Y", strtotime(__($poData['required_date'])));
                                ?></td>
                        </tr>
                    </table>
                    <br>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="col-1 order-info-box">
    <div class="entry-edit-head">
        <h4><?php echo __('PO Comment History'); ?></h4>
    </div>
    <fieldset>
        <div id="order_history_block">
            <ul class="note-list">
                <?php
                for ($i = 0; $i < count($poCommentsCol); $i++) {
                    ?>
                    <li>
                        <strong><?php echo date("M d, Y", strtotime(__($poCommentsCol[$i]['created_at']))); ?></strong>&nbsp;<?php echo date("h:i:s A", strtotime(__($poCommentsCol[$i]['created_at']))); ?>
                        <br>
                        <?php echo $poCommentsCol[$i]['comment']; ?>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </fieldset>
</div>
<div class="buttons-set">
    <p class="back-link">
        <a href="<?php echo $block->getUrl('inventorysystem/supplierorder/vieworder'); ?>">
            <small>« </small>
            Back
        </a>
    </p>
</div>