<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Xsearch
 */
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
//$block= $block->getLayout()->createBlock('Amasty\Xsearch\Block\Widget\Search');

    /** @var $helper \Magento\Search\Helper\Data */
    $helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<?php /**
<div class="block block-search block-xsearch">
    <div class="block block-title"><strong><?= $block->escapeHtml(__('Search')) ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch xsearch-mini-form-widget"
              action="<?= $block->escapeUrl($block->getHelper()->getResultUrl()) ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= $block->escapeHtml(__('Search')) ?></span>
                </label>
                <div class="control">
                    <input data-bind='mageInit: {"quickSearch":{ "formSelector":".xsearch-mini-form-widget",
                                "url":"<?= $block->escapeUrl($block->getHelper()->getSuggestUrl())?>",
                                "destinationSelector":".xsearch-autocomplete-widget",
                                "minSearchLength":"<?= $block->escapeHtml($block->getHelper()->getMinQueryLength()) ?>"}}'
                           type="text"
                           name="<?= $block->escapeHtmlAttr($block->getHelper()->getQueryParamName()) ?>"
                           value="<?=  $block->getHelper()->getEscapedQueryText() ?>"
                           placeholder="<?= $block->escapeHtmlAttr(__('Search entire store here...')) ?>"
                           class="input-text search_input_text"
                           maxlength="<?= $block->escapeHtmlAttr($block->getHelper()->getMaxQueryLength()) ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           aria-expanded="false"/>
                    <div class="search-autocomplete xsearch-autocomplete-widget"></div>
                    <?php $preloadHtml = $block->getPreloadHtml(); ?>
                    <?php if ($preloadHtml): ?>
                        <div class="amasty-xsearch-preload" data-amsearch-js="preload">
                            <?= $preloadHtml;?>
                        </div>
                    <?php endif;?>
                    <?= $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtml(__('Search')) ?>"
                        class="action search"
                        aria-label="Search"
                >
                    <span><?= $block->escapeHtml(__('Search')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
 */
?>

<div class="block block-search">
    <div class="block block-title"><strong><?= /* @escapeNotVerified */ __('Search') ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= /* @escapeNotVerified */ __('Search') ?></span>
                </label>
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
                           value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
                           placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...') ?>"
                           class="input-text"
                           maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?= /* @escapeNotVerified */ __('Search') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>

