<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Actions $block */
?>
<?php $children = $block->getChildNames(); ?>
<?php if ($children): ?>
    <td class="<?= $block->escapeHtmlAttr($block->getCssClass()) ?>">
        <?php foreach ($children as $childName):?>
            <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
        <?php endforeach;?>
    </td>
<?php endif; ?>
