<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
?>
<?php if (!$_productCollection->count()): ?>
	<div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else:
	?>
	<?= $block->getAdditionalHtml() ?>
	<?php
	if ($block->getMode() == 'grid') {
		$viewMode = 'grid';
		$image = 'category_page_grid';
		$showDescription = false;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	} else {
		$viewMode = 'list';
		$image = 'category_page_list';
		$showDescription = true;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
	}
	/**
	 * Position for actions regarding image size changing in vde if needed
	 */
	$pos = $block->getPositioned();
	?>
	<div class="col-lg-9 col-md-9 products-wrapper">
		<div class="col-xs-12 title-wrapper clearfix">

				    <!--<h3 class="title"><?php //echo '<pre>'.$catName; print_r($block->getCurrentCategory());die('here');   ?></h3>-->
			<div class="mb-filter">
				<button class="btn"><i class="fa fa-filter"></i> Filter</button>
			</div> 

			<h3 class="title"><?php //echo $this->getLayer()->getCurrentCategory()->getName()   ?></h3>

			<div class="custom-select-my floater-left">
				<?= $block->getToolbarHtml() ?>
			</div>

		</div>
		<div class="products-row equalheight_wrapper clearfix">
			<?php foreach ($_productCollection as $_product): ?>
				<div class="col-md-4 col-sm-4 col-xs-6 product-box">
					<div class="product-inner-box product<?= $block->escapeHtml($_product->getId()) ?>">
						<div class="txt-content equalheight">
							<div class="img-box">
								<button  data-role="add-to-links" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' class="btn btn-wishlist action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"><i class="fa fa-heart"></i></button>
								<!--<a class="btn btn-wishlist" href="#"><i class="fa fa-heart" aria-hidden="true"></i></a>-->
								<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product-thumbnail">
									<img class="product-img img-responsive" src="<?= $block->getImage($_product, $image)->getImageUrl(); ?>">
								</a>
							</div>
							<h3 class="product-title">
								<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
									<?php									
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									if(strlen($_productNameStripped) > 50){
										echo substr($_productNameStripped, 0, 50).'...';
									}else{
										echo $_productNameStripped;
									}
									?>
								</a>
							</h3>
							<p class="product-desc">
								<?php 
									$_productDescStripped = $_product->getShortDescription();
									if(strlen($_productDescStripped) > 30){
										echo substr($_productDescStripped, 0, 30).'...';
									}else{
										echo $_productDescStripped;
									}
									?>
							</p>
							
						</div>
						
					</div>
				</div>
			<?php endforeach; ?>
		</div>
		<?php echo $block->getToolbarHtml() ?>
	</div>
	
	<?php if (!$block->isRedirectToCartEnabled()) : ?>
		<script type="text/x-magento-init">
			{
			"[data-role=tocart-form], .form.map.checkout": {
			"catalogAddToCart": {
			"product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
			}
			}
			}
		</script>
	<?php endif; ?>
<?php endif; ?>
