<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
$label_new_status = $this->helper('Rptech\General\Helper\Data')->getLabelNewStatus();
$label_sale_status = $this->helper('Rptech\General\Helper\Data')->getLabelSaleStatus();
$label_sold_status = $this->helper('Rptech\General\Helper\Data')->getLabelSoldStatus();
$label_new = $this->helper('Rptech\General\Helper\Data')->getLabelNewImage();
$label_sale = $this->helper('Rptech\General\Helper\Data')->getLabelSaleImage();
$label_sold = $this->helper('Rptech\General\Helper\Data')->getLabelSoldImage();
?>
<?php if (!$_productCollection->count()): ?>
	<div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	<?= $block->getToolbarHtml() ?>
	<?= $block->getAdditionalHtml() ?>
	<?php
	if ($block->getMode() == 'grid') {
		$viewMode = 'grid';
		$image = 'category_page_grid';
		$showDescription = false;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	} else {
		$viewMode = 'list';
		$image = 'category_page_list';
		$showDescription = true;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
	}
	/**
	 * Position for actions regarding image size changing in vde if needed
	 */
	$pos = $block->getPositioned();
	?>
	<div class="col-lg-9 col-md-9 products-wrapper">
		<div class="col-xs-12 title-wrapper clearfix">

				    <!--<h3 class="title"><?php //echo '<pre>'.$catName; print_r($block->getCurrentCategory());die('here');   ?></h3>-->
			<div class="mb-filter">
				<button class="btn"><i class="fa fa-filter"></i> Filter</button>
			</div> 

			<h3 class="title"><?php //echo $this->getLayer()->getCurrentCategory()->getName()   ?></h3>

			<div class="custom-select-my floater-left">
				<?= $block->getToolbarHtml() ?>
			</div>

		</div>
		<div class="products-row equalheight_wrapper clearfix">
			<?php foreach ($_productCollection as $_product): ?>
				<div class="col-md-4 col-sm-4 col-xs-6 product-box">
					<div class="product-inner-box product<?= $block->escapeHtml($_product->getId()) ?>">
						<div class="txt-content equalheight">
							<?php
                        	$class = '';
                        	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
			                $media_url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()
			                                        ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
			                $stock_item = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItemBySku($_product->getSku());
                            if(!$stock_item->getIsInStock()==1) {
                                $class = "product-sold";
                            } 
                            else if ($_product->getSpecialPrice() && $_product->getFinalPrice() == $_product->getSpecialPrice() && $_product->getIsSalable()) {
                                $class = "product-sale";
                            }
                            else if($_product->getNewsFromDate() || $_product->getNewsToDate()) {
                                $from_date = date('d/m/Y',strtotime($_product->getNewsFromDate()));
                                $to_date = date('d/m/Y',strtotime($_product->getNewsToDate()));
                                $today = date('d/m/Y');
                                if($from_date<$today || $to_date>$today || ($from_date<$today && $today<$to_date)) {
                                    $class = "product-new";
                                }
                            }
                            ?>
                            <div class="product-tag <?= $class; ?>">
                                <?php
                                if($label_sold_status && !$stock_item->getIsInStock()==1) {
                                    echo "<img class='tag-sold' src='".$media_url.'catalog/product/label/'.$label_sold."' />";
                                }
                                else if ($label_sale_status && $_product->getSpecialPrice() && $_product->getFinalPrice() == $_product->getSpecialPrice() && $_product->getIsSalable()) {
                                    echo "<img class='tag-sale' src='".$media_url.'catalog/product/label/'.$label_sale."' />";
                                }
                                else if($_product->getNewsFromDate() || $_product->getNewsToDate()) {
                                    $from_date = date('d/m/Y',strtotime($_product->getNewsFromDate()));
                                    $to_date = date('d/m/Y',strtotime($_product->getNewsToDate()));
                                    $today = date('d/m/Y');
                                    if($label_new_status && ($from_date<$today || $to_date>$today || ($from_date<$today && $today<$to_date))) {
                                        echo "<img class='tag-new' src='".$media_url.'catalog/product/label/'.$label_new."' />";
                                    }
                                }
                                ?>
                            </div>
							<div class="img-box">
								<button  data-role="add-to-links" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' class="btn btn-wishlist action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"><i class="fa fa-heart"></i></button>
								<!--<a class="btn btn-wishlist" href="#"><i class="fa fa-heart" aria-hidden="true"></i></a>-->
								<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product-thumbnail">
									<img class="product-img img-responsive" src="<?= $block->getImage($_product, $image)->getImageUrl(); ?>">
								</a>
							</div>
							<h3 class="product-title">
								<!-- Test by Hemant -->
								<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
									<?php 
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									if(strlen($_productNameStripped) > 15){
										echo substr($_productNameStripped, 0, 15).'...';
									}else{
										echo $_productNameStripped;
									}
									?>
								</a>
							</h3>
							<p class="product-desc">
								<?php 
									$_productDescStripped = $_product->getShortDescription();
									if(strlen($_productDescStripped) > 50){
										echo substr($_productDescStripped, 0, 50).'...';
									}else{
										echo $_productDescStripped;
									}

									/* Location */
									$attr = $_product->getResource()->getAttribute('location');
									$optionId = $_product->getLocation();
									if(strstr($optionId, ",")) {
										//echo $optionId;
										$opt_ary = explode(",", $optionId);
										foreach($opt_ary as $optionId) {
											if ($attr->usesSource()) {
												echo $attr->getSource()->getOptionText($optionId);
											}
										}
									} else {
										if ($attr->usesSource()) {
											echo $attr->getSource()->getOptionText($optionId);
										}
									}
									?>
							</p>
							<?php if($_product->getFinalPrice() > 0):?>
							<p class="price-tag">
								<?php echo $priceHelper->currency($_product->getFinalPrice(), true, false); ?>
							</p>
							<?php endif;?>
						</div>
						<!--<div class="clearfix btn-wrapper">
							<span style="display: none" class="prosku"><?php echo $_product->getSku(); ?></span>
							<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="btn btn-view">View</a>
							<?php $postParams = $block->getAddToCartPostParams($_product); ?>
							<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
								<input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
								<input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
								<?= $block->getBlockHtml('formkey') ?>
								<?php
								$sell_status = $_product->getResource()->getAttribute('sell_status')->getFrontend()->getValue($_product);
								if ($sell_status == 'Yes' && $_product->getFinalPrice() > 0 && $_product->getIsSalable()) {
									?>
									<button type="submit"
										title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
										class="action tocart primary btn btn-cart">
										<span><i class="fa fa-shopping-cart"></i><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
									</button>
								<?php } else { ?>
								<span style="display: none" class="prosku"><?php echo $_product->getSku(); ?></span>
									<a class="btn btn-enq" id="product<?= $block->escapeHtml($_product->getId()) ?>">Send Enquiry</a>
								<?php } ?>
							</form>
						</div>-->
					</div>
				</div>
			<?php endforeach; ?>
		</div>
		<?php echo $block->getToolbarHtml() ?>
	</div>
	
	<?php if (!$block->isRedirectToCartEnabled()) : ?>
		<script type="text/x-magento-init">
			{
			"[data-role=tocart-form], .form.map.checkout": {
			"catalogAddToCart": {
			"product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
			}
			}
			}
		</script>
	<?php endif; ?>
<?php endif; ?>
