<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLoginFree
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>


<section class="login-section">
    <div class="container"> 
        <div class="row">               
            <div class="login-wrapper">
                <div class="t-row">
                    <div class="col-left col-sm-6 col-xs-12">
                        <div class="inner-column">
                            <h1 class="title">Login into your Account </h1>
                            <form class="form form-login"
                                  action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                                  method="post"
                                  id="login-form"
                                  data-mage-init='{"validation":{}}'>
                                      <?= $block->getBlockHtml('formkey') ?>
                                <div class="form-group">
                                    <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="form-control" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                                    <label class="input_label">Email</label>
                                </div>
                                <div class="form-group">
                                    <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="form-control" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                                    <label class="input_label">Password</label>
                                </div>
                                <?= $block->getChildHtml('form_additional_info') ?>
                                <div class="clearfix btn-wrapper">
                                    <div class="btn-row">
                                        <button class="btn">Sign In</button>
                                        <a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a>
                                    </div>
                                </div>
                                <?php
                                $block1 = $this->getLayout()->createBlock('Magento\Customer\Block\Form\Login\Info');
                                ?>
                                <p class="txt">Don't have an account?  <a href="<?= $block1->escapeUrl($block1->getCreateAccountUrl()) ?>" class="action link"><?= $block1->escapeHtml(__('Create an Account')) ?></a></p>
                            </form>

                        </div>
                    </div>
                    <div class="col-right col-sm-6 col-xs-12">
                        <div class="inner-column">
                            <?php echo $this->getChildHtml('pslogin_buttons'); ?>
                            <!--                                    <a href="#" class="login-options login-guest clearfix">
                                                                    <span class="icon"><i class="fa fa-user login-option-icon"></i></span>
                                                                    <span class="">Sign In with Guest</span>
                                                                </a>-->
                            <!--                            <a href="#" class="login-options login-fb clearfix">
                                                            <span class="icon"><i class="fa fa-facebook-f  login-option-icon"></i></span>
                                                            <span>Sign In with Facebook</span>
                                                        </a>-->
                           
                            <!--                            <a href="" class="login-options login-twit clearfix">
                                                            <span class="icon"><i class="fa fa-twitter login-option-icon"></i></span>
                                                            <span>Sign In with Twitter</span>
                                                        </a>
                                                        <a href="" class="login-options login-google clearfix">
                                                            <span class="icon"><i class="fa fa-google-plus login-option-icon"></i></span>
                                                            <span>Sign In with Google +</span>
                                                        </a>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php echo $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?php echo $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?php echo $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?php echo $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php echo $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php echo $block->escapeHtml(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?php echo $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php echo $block->escapeHtml(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php echo $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="secondary"><a class="action remind" href="<?php echo $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?php echo $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>

                <?php
                $helper = $this->helper('Plumrocket\SocialLoginFree\Helper\Data');
                if($helper->modulePositionEnabled('login') && $helper->hasButtons()) : ?>
                    <div class="pslogin-spacer pslogin-clearfix">
                        <table>
                            <tr>
                                <td><div class="pslogin-border"></div></td>
                                <td class="pslogin-bordertext w25"><?php echo __('OR'); ?></td>
                                <td><div class="pslogin-border"></div></td>
                            </tr>
                        </table>
                    </div>
                    <?php echo $this->getChildHtml('pslogin_buttons'); ?>
                <?php endif; ?>
            </fieldset>
        </form>
    </div>
</div>-->

