<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php
$product = $block->getProduct();
$attributeSetId = $product->getAttributeSetId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var  $coll \Magento\Eav\Model\ResourceModel\Entity\Attribute\Collection */
$groupCollection = $objectManager->create('Magento\Eav\Model\ResourceModel\Entity\Attribute\Group\Collection');
$groupCollection->addFieldToFilter('attribute_set_id', $attributeSetId);
$groupCollection->addFieldToFilter('tab_group_code', array('null' => true));
$groupCollection->addFieldToFilter('attribute_group_code', array('neq' => 'magemob-inventory'));
$groupCollection->addFieldToFilter('attribute_group_code', array('neq' => 'gift-options'));
$groupCollection->addFieldToFilter('attribute_group_code', array('neq' => 'bundle-items'));
$groupCollection->setOrder('sort_order', 'ASC');
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
?>
<?php if ($product->getTypeId() != "bundle") { ?>
	<div class="avail-check">
		<input type="text" maxlength="6" name="pincode_check" id="pincode_check" class=""/>
		<button type="submit" id="checkpincode" class="btn">Pincode Check<span id="spanpinloader" style="display: none;"><img class="pincodeloaderImg" src="<?php echo $this->getViewFileUrl('images/pincodeloader.gif'); ?>"></span></button>
		<span id="showpincodemsg"></span>
		<div class="errorDiv" style="color: red;">
			<span id="errorMsg"></span>
		</div>


	</div>
<!-- product description -->

<div class="para"><?= $product->getDescription() ?></div>
	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
		<div class="panel panel-default">
			<a class="collapsed" role="button" data-toggle="collapse"  style="text-decoration: none;">
				<div class="panel-heading" role="tab" id="headingTwo" style="color: black;">
					<h4 class="panel-title heading">
						Specification
					</h4>
				</div>
			</a>
		</div>
		<?php
		$i = 0;
		$productAttributes = $product->getAttributes();

		foreach ($groupCollection as $gp) {
			$group = $gp->getData();
			$group_id = $group['attribute_group_id'];
			?>
			<?php
			$attrs = array();
			//echo '<pre>';
			foreach ($productAttributes as $attribute) {
				//print_r($attribute);
				if (($attribute->isInGroup($attributeSetId, $group_id) && $attribute->getFrontend()->getValue($product) != '') || $attribute->getFrontend()->getLabel() == 'Processor Specifications') {
					$attrs[] = $attribute->getFrontend();
				}
			}
			//echo '</pre>';
			?>
			<div class="panel panel-default abc2">
				<a class="ext" role="button" data-toggle="collapse" data-parent="#accordion" href="#<?php echo $group['attribute_group_code']; ?>" aria-expanded="true" aria-controls="<?php echo $group['attribute_group_name']; ?>" style="text-decoration: none;">
					<div class="panel-heading" role="tab" id="heading<?php echo $group_id; ?>" style="color: black;">
						<h4 class="panel-title">
							<?php echo $group['attribute_group_name']; ?>
						</h4>
					</div>
				</a>
				<div id="<?php echo $group['attribute_group_code']; ?>" class="panel-collapse collapse <?php echo($i == 0) ? 'in' : ''; ?> " role="tabpanel" aria-labelledby="heading<?php echo $group_id; ?>">
					<div class="panel-body">
						<?php if (count($attrs) > 1) { ?>
							<table>
								<?php
								foreach ($attrs as $single) {
									?>
									<tr>
										<td width="200px">
											<?php
											echo '<b>'.$single->getLabel().':</b>';
											?>
										</td>
										<th><?php
											$val = $single->getValue($product);
											echo $val;
											?></th>
									</tr>
									<?php
								}
								?>
							</table>
							<?php
						} else {
							foreach ($attrs as $single) {
								?>
									<tr>
										<td width="200px">
											<?php
											echo '<b>'.$single->getLabel().':</b>';
											?>
										</td>
										<th><?php
											$val = $single->getValue($product);
											echo $val;
											?></th>
									</tr>
									<?php
							}
						}
						?>
					</div>
				</div>
			</div>
			<?php
			$i++;
		}
		?>
	</div>
	<script type="text/javascript">
		require(['jquery'], function ($) {
			$(document).ready(function () {
				$("#checkpincode").click(function () {
					$("#spanpinloader").show();
	<?php
	header('Access-Control-Allow-Origin: *');
	header('Authorization: Token f939438eba9c2d712539be8fc9991c056a142696');
	?>
					var pincode = $("#pincode_check").val();
					var flag = true;
					if (isNaN(pincode)) {
						flag = false;
					}
					if (pincode) {
						//alert(pincode + "==>not empty")
						//call remote api to check pincode
						if (flag) {
							var api_url = 'https://staging-express.delhivery.com/c/api/pin-codes/json/'
							var key = '5b578yg9yvi8sogirbvegoiufg9v9g579gviuiub8' // not real
							$.ajax({
								url: 'callRemoteApi.php', //api_url + "?filter_codes=" + pincode,
								type: 'GET',
								dataType: 'json',
								data: {pincode: pincode},
								contentType: 'application/json',
								success: function (result) {
									$("#spanpinloader").hide();
									var msg;
									if (result > 0) {
										msg = "This product can be delivered on given pincode";
									} else {

										msg = "This product not delivered on given pincode";
									}
									$("#showpincodemsg").text(msg);
								},
								error: function (error) {
									console.log(error);
								}
							});

						} else {
							$("#spanpinloader").hide();
							alert('Please enter numebers only');

						}

					} else {
						$("#spanpinloader").hide();
						alert('Please enter pincode');
					}
				});
			});
		});
	</script>
<?php } ?>