<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$Shipment = $objectManager->create('\Magento\Sales\Model\Order\Shipment')->load($this->getRequest()->getParam('shipment_id'));


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('\Magento\Sales\Model\Order')->load($Shipment->getOrderId());
$shippingAddress = $order->getShippingAddress();
	
$postcode=$shippingAddress->getPostcode();
?>
<?php /** @var $block Magento\Shipping\Block\Adminhtml\Order\Tracking\View */ ?>
<div class="admin__control-table-wrapper">
    <table class="data-table admin__control-table" id="shipment_tracking_info">
        <thead>
            <tr class="headings">
                <th class="col-carrier"><?= /* @escapeNotVerified */ __('Carrier') ?></th>
                <th class="col-title"><?= /* @escapeNotVerified */ __('Title') ?></th>
                <th class="col-number"><?= /* @escapeNotVerified */ __('Number') ?></th>
                <th class="col-delete last"><?= /* @escapeNotVerified */ __('Action') ?></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td class="col-carrier">
                    <select name="carrier"
                            class="select admin__control-select"
                            onchange="selectCarrier(this)">
                        <?php foreach ($block->getCarriers() as $_code => $_name): ?>
                        <option value="<?= /* @escapeNotVerified */ $_code ?>"><?= $block->escapeHtml($_name) ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td class="col-title">
                    <input class="input-text admin__control-text"
                           type="text"
                           id="tracking_title"
                           name="title"
                           value="" />
                </td>
                <td class="col-number">
                    <input class="input-text admin__control-text"
                           type="text"
                           id="tracking_number"
                           name="number"
                           value="" />
                </td>
                <td class="col-delete last"><?= $block->getSaveButtonHtml() ?></td>
            </tr>
        </tfoot>
    <?php if ($_tracks = $block->getShipment()->getAllTracks()): ?>
        <tbody>
        <?php $i = 0; foreach ($_tracks as $_track):$i++ ?>
            <tr class="<?= /* @escapeNotVerified */ ($i%2 == 0) ? 'even' : 'odd' ?>">
                <td class="col-carrier"><?= $block->escapeHtml($block->getCarrierTitle($_track->getCarrierCode())) ?></td>
                <td class="col-title"><?= $block->escapeHtml($_track->getTitle()) ?></td>
                <td class="col-number">
                    <?php if ($_track->isCustom()): ?>
                    <?= $block->escapeHtml($_track->getNumber()) ?>
                    <?php else: ?>
                    <a href="#" onclick="popWin('<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($_track) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')"><?= $block->escapeHtml($_track->getNumber()) ?></a>
                    <div id="shipment_tracking_info_response_<?= /* @escapeNotVerified */ $_track->getId() ?>"></div>
                    <?php endif; ?>
                </td>
                <td class="col-delete last"><button class="action-delete" type="button" onclick="deleteTrackingNumber('<?= /* @escapeNotVerified */ $block->getRemoveUrl($_track) ?>'); return false;"><span><?= /* @escapeNotVerified */ __('Delete') ?></span></button></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
    </table>
</div>

<script>
require(['prototype','jquery', 'jquery/ui'], function($){

//<![CDATA[
function selectCarrier(elem) {
    var option = elem.options[elem.selectedIndex];
    jQuery('#tracking_title').value = option.value && option.value != 'custom' ? option.text : '';
	
	document.getElementById("tracking_title").value=(option.value && option.value != 'custom') ? option.text : '';
            //var elem = Event.element(event);
			var textboxid = elem.id.replace('trackingC','trackingN');
			jQuery(textboxid).disabled = false;
			jQuery(textboxid).value = '';
            var option = elem.options[elem.selectedIndex];
			 if (option.value && option.value == 'delhivery') {
				 //submitAjaxData(elem.id);
				// alert("delhivery");
				 var url ="<?php echo $this->helper('Magento\Backend\Helper\Data')->getUrl('delhivery_lastmile/awb/getawb/') ?>";
				   new Ajax.Request(url, {
						method:'post'
						, parameters: {   
							 zipcode: '<?php echo $postcode?>',
							 orderid: '<?php echo $order->getId();?>'
							} 
						, requestHeaders: {Accept: 'application/json'},
						onSuccess: function(transport) {
							retjson = transport.responseText.evalJSON();
							//var textboxid = valueofrow.replace('trackingC','trackingN');
							document.getElementById("tracking_number").setAttribute("readonly", "true");
							if(/\d{1,9}/.test(retjson.resp[0].awb))
								document.getElementById("tracking_number").value = retjson.resp[0].awb;
							else
								alert(retjson.resp[0].awb);
						 }
					}); 			 
			 }else
			 {
				 document.getElementById("tracking_number").value="";
				 document.getElementById("tracking_number").setAttribute("readonly", "false");
			 }
			
        
}

function deleteTrackingNumber(url) {
    if (confirm('<?= /* @escapeNotVerified */ __('Are you sure?') ?>')) {
        submitAndReloadArea($('shipment_tracking_info').parentNode, url)
    }
}

window.selectCarrier = selectCarrier;
window.deleteTrackingNumber = deleteTrackingNumber;
//]]>

});
</script>
